### ISSUE TITLE
Blog posts for Bits premiere

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbachecks#211]
Hello,
Please schedule a blog post about dbachecks that we will promote for Bits.

You can talk about anything - @Tonyw72 will be sharing code that he uses to time his CMS Groups

Duplicate topics are totally acceptable. If I have time, I'll try to talk about each topic on the readme, one by one.

**Comment by SQLDBAWithABeard** [comment]
THANK YOU so very much for all the posts :-)
