### ISSUE TITLE
New Check - user/login checks

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbachecks#238]
- Database users exist as server logins (unless they are contained databases).
- Non SQL Logins exist in AD

**Comment by PsPsam** [comment]
created a PR https://github.com/sqlcollaborative/dbachecks/pull/404 for this not sure if it covers what is needed. I only did a check for the ad usrs and groups. 

There is a test for orphaned users in the database checks and I think with PR404 this will cover this issue.

**Comment by SQLDBAWithABeard** [comment]
this has ben completed
