### ISSUE TITLE
Export dbachecks results to a database (and SSRS report?)

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#270]
It would be good to be able to export the results to a database and potentially create an SSRS report (maybe that should be another issue?)

I think I could see it as being done in this way with the database instance, name and table held in the config and using Write-DbaDataTable

````Invoke-DbcCheck -Show Fails -PassThru | Write-DbcDbTable

**Comment by michalporeba** [comment]
The simple export of the results to a database table would be as simple as piping the output to `Out-DbaDataTable`. Wouldn't that be prefered to adding a new set of parameters? 

However, I would see value in configurable table output which then can be set in an environment configuration file making sure that tests for a specific environment will always go to a specific table, automatically.

**Comment by SQLDBAWithABeard** [comment]
Yes yes yes @michalporeba  that is definitely the way forward

**Comment by SQLDBAWithABeard** [comment]
I like the idea of doing this but I'm going to close this issue for now. I think we should handle any resulting action on the output of the checks via seperate commands rather than within dbachecks - If need be we can have an additional module dbachecks-actions forexample
