### ISSUE TITLE
Pester 4.3.1 "is not catalog signed," dbachecks module installation fails

### ISSUE THREAD

**Issue by sql-underworld** [sqlcollaborative/dbachecks#292]
I'm still able to install the dbachecks module using -SkipPublisherCheck but would rather have not done so (we're in the middle of external pen testing and this error made me Spock an eyebrow).

Full error mssg:
PackageManagement\Install-Package : The version '4.3.1' of the module 'Pester' being installed is not catalog signed. Ensure that the version '4.3.1' of the module 'Pester' has the catalog file 'Pester.cat' 
and signed with the same publisher 'CN=Microsoft Root Certificate Authority 2010, O=Microsoft Corporation, L=Redmond, S=Washington, C=US' as the previously-installed module '4.3.1' with version '3.4.0' under 
the directory 'C:\Program Files\WindowsPowerShell\Modules\Pester\3.4.0'. If you still want to install or update, use -SkipPublisherCheck parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1809 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : ModuleIsNotCatalogSigned,Validate-ModuleAuthenticodeSignature,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

**Comment by potatoqualitee** [comment]
Yeah, unfortunately Pester can be pesky ;) We have no solution other than trying to let people know. This should be resolved with

```powershell
Install-Module Pester -SkipPublisherCheck -Force
Import-Module Pester -Force
````

dbachecks.io/install
