### ISSUE TITLE
powerBI Warning - 

### ISSUE THREAD

**Issue by seadba** [sqlcollaborative/dbachecks#296]
this looks awesome - however, i get the following message after running update-DbcPowerBiDatasource- i have power bi installed –

PS C:\WINDOWS\system32> start-DbcPowerBi
WARNING: [14:28:17][Start-DbcPowerBi] .pbix not associated with any program. Please (re)install Power BI

**Comment by gbargsley** [comment]
Do you have the latest PowerBI installed from this location?
https://powerbi.microsoft.com/en-us/desktop/

**Comment by seadba** [comment]
thanks for the fast response - i did , but i took a powerbi class last month, and the instructor suggested installing from microsoft store as that will update the install monthly - i was testing brent ozars sp_blitz powerbi yesterday - worked well -

**Comment by gbargsley** [comment]
Are you able to open the PBIX manually from PowerBI Desktop?

**Comment by seadba** [comment]
yes, just did -that works well - very cool - looks like it cant find the pbix in ps - is there a config setting for this cmd?  thanks

**Comment by gbargsley** [comment]
I don't think so.  It seems like a file association issue with PowerBi and pbix files.  Will have to ask some of the others.  @ClaudioESSilva @potatoqualitee @SQLDBAWithABeard

**Comment by seadba** [comment]
thanks - its awesome - was able to publish this with no issues - very slick tool

**Comment by ClaudioESSilva** [comment]
Hi @seadba,
Cab you run the following instruction and let us know the output? 
```Get-ItemProperty "Registry::HKEY_Classes_root\.pbix" ```

**Comment by seadba** [comment]
nothing

PS C:\WINDOWS\system32> Get-ItemProperty "Registry::HKEY_Classes_root\.pbix"
PS C:\WINDOWS\system32>

**Comment by ClaudioESSilva** [comment]
Thanks! 
That is the way we are validating the path for PowerBI. Maybe the installation from the store keep the value on another key, we will take a look.

**Comment by seadba** [comment]
no worries - thanks for the fast response - this tool is great - 

i tried this as well

PS C:\WINDOWS\system32> Start-DbcPowerBi -Path "C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.0.0\bin\dbachecks
.pbix"
WARNING: [15:04:55][Start-DbcPowerBi] .pbix not associated with any program. Please (re)install Power BI

**Comment by ClaudioESSilva** [comment]
Yeah, that parameter is for selecting the Power BI file. But, we still validate if the registry key.  Because it is missing, you get the error message.

**Comment by wsmelton** [comment]
@claudio Windows apps are installed in a hidden directory under program files.

**Comment by wsmelton** [comment]
I verified on my machine that Microsoft Store apps are found under `C:\Program Files\WindowsApps` . Which this is a hidden system folder that normal users will not have access to by default.

I could find no registry key for the apps I have installed via the store.

**Comment by ClaudioESSilva** [comment]
Thanks for the confirmation @wsmelton!
Until we find a better way, I think we should use a `-Force` parameter or a `-
 SkipPBIValidation` to ignore the actual validation.

**Comment by potatoqualitee** [comment]
Please see #311 and confirm if that's a valid way. I'm good with it.

**Comment by seadba** [comment]
i  just tested on a 2012 box with the regular download - works perfectly

**Comment by potatoqualitee** [comment]
excellent!
