### ISSUE TITLE
Suspend-DbcCheck - Suppressing of known problems for a (short) period of time. 

### ISSUE THREAD

**Issue by michalporeba** [sqlcollaborative/dbachecks#300]
Some of the errors are critical enough to drop everything and go fixing. Some are not. 

I was thinking about ability to have a 'severity' settings for errors. So disk space at 30% would be a warning, that we need to do something, perhaps order a new disk, but at 10% it's probably time to go and get the disk yourself if 'provisioning' got kicked in the long grass of project management. That is difficult as it would require changes to Pester. Alternative would be to simply set the test at the warning level, but that means we would be pestered with known problem we are dealing with already and which is not critical yet. Seeing, or worse, expecting failures in the checks could lead to missing a new problem. 

So how about suppression mechanism? After running a test, when required action has been initiated or scheduled, one could do something like `Suspend-DbcCheck -SqlInstance $instance -DatabaseName $database -Check policy.mycheck -ForDays 7`. That check then would either pass, or not be run for the specified period of time unless we really want to see all of the errors again which could be achieved with `Invoke-DbcCheck -IncludeSuspended` option. You could even add second threshold value to the policy configuration like `policy.diskspace.percentfree.critical` after reaching which the suspension would be ignored.

I realise that probably not that many of the current 80 checks is like policy.diskspace where it might be useful, but if it was implemented in such a way that it can be used by custom checks I could see it useful for a number of my checks which in itself are not mission critical, and apply to the processes using SQL Server, but which I know will become critical if ignored for too long. 

Suspensions could be stored locally in a json file and could be shared using a repo, or could be centralised through a database. 

What do you think? I'm happy to work on the implementation but would like to have some opinions first.

**Comment by SQLDBAWithABeard** [comment]
I get the problem

When this came up in our pre-con - off the top of my head I suggested a seperate config for each warning level as  Pester is Pass or Fail there is no other level we can use easily and I do not want to get away from a test result is Pass or it is Fail

So you can run the immediate action test configurationn every day adn the warning test cofiguration every week 

I like this idea of a configuration item i worry about it getting very complex very quickly and making it difficult or new people to easily get into using dbachecks

**Comment by michalporeba** [comment]
That was actually my question in the pre-con. Two separate configurations go only so far and they cover only the scenario where we have a warning and error level. A slightly different is with errors that take time to rectify. Do we want to see them red all the time? It ties with the JIRA integration too. 

I'm not sure how to best implement my proposed solution to make it easy, but I'm sure it would have to be easy to use to be useful. Perhaps using the `-Skip` of `It`? Perhaps some conditional logic outside of `It`? 

Let's leave it here for now. I got busy looking at the performance of the tests which is absolutely essential for me to be able to use it outside of few little dev servers I have. I'll come back to it and think about it some more.

**Comment by SQLDBAWithABeard** [comment]
The more discussion there is about this the more I think that this is not functionality that we should be putting into dbachecks. I think a different configuration is the best way to answer this one

**Comment by michalporeba** [comment]
I still think that different configuration doesn't resolve my problem, but the more we discuss it and the more I understand the internals of dbachecks, I think it might be a separate function within the project or in another module, to which we could pipe the results from Invoke-DbaCheck and that would create jira tickets, or sent a slack message, or allow for suppression.

**Comment by SQLDBAWithABeard** [comment]
I'm going to close this issue for now. I think we should handle any resulting action on the output of the checks via seperate commands rather than within dbachecks - If need be we can have an additional module dbachecks-actions forexample
