### ISSUE TITLE
New Check - Files about to grow

### ISSUE THREAD

**Issue by michalporeba** [sqlcollaborative/dbachecks#301]
How about a new check to alert about database files which are too full, and about to grow so that the size can be managed off hours? A check like that would hopefully allow to avoid the Database Growth Event errors which are already included.

**Comment by potatoqualitee** [comment]
i dig

**Comment by SQLDBAWithABeard** [comment]
+1 from me

config for percent full and a test a bit like the identity column one would do this??

**Comment by michalporeba** [comment]
I think that should be percentage of the last increment. So if we set it to 80% and the growth is 100MB then the test should fail when there is less than 20MB free in the file. It reminds me of another test I wanted to add, a database file which will not be able to grow any more as there is not enough disk space for the next increment. 

It will be easy to implement, but I'd like to have make the current database tests to go sufficiently fast for me to use them before I will start adding new tests.

**Comment by tootblan** [comment]
Anybody mind if I take this one? Seems like it'd be an easy first PR.

**Comment by SQLDBAWithABeard** [comment]
That would be awesome :-) @tootblan

**Comment by SQLDBAWithABeard** [comment]
Thank you @tootblan Its in the gallery now :-)
