### ISSUE TITLE
Failed alert to JIRA ticket

### ISSUE THREAD

**Issue by michalporeba** [sqlcollaborative/dbachecks#305]
Would something like automatically creating a JIRA ticket be even in the scope of dbachecks? We want to automate as many checks as possible so we are not bother by people coming and asking for stuff. Writing checks for support, and allowing them run it is one thing, but if the checks were automated to the point where the support task is raised before they even know they have a problem that would hopefully make them fix it before they even think of coming and asking for help. 

That would require some persistence of data (like #300 or #303) to avoid raising the same ticket again and again if the previous is still open.

**Comment by SQLDBAWithABeard** [comment]
Beautiful :-)

There is no reason why this cannot be done

It would be easier to interact with this

https://github.com/AtlassianPS/JiraPS 

I would think and add some config items for the JIRA as well

**Comment by SQLDBAWithABeard** [comment]
Also

So I would say that we keep the notification ( Power Bi, Email, XML, Teams, Slack, JIRA outside of Invoke-DbcChecks and pipe to each command.

The Show parameter is only for output to screen

I would prefer

Invoke-DbcCheck -Show none -SendTo email sends to default email address
to be
Invoke-DbcCheck -Show none  -PassThru | Send Email -All

Sends entire results via email

and 

Invoke-DbcCheck -Show None | Send-DbcSlack -Fails

Send Test Failure to slack channel 

Invoke-DbcCheck -Show None | New-DbcJira -Fails

Runs tests without outputting to screen and open a Jira Tick for the failure

We can add the config items for each "notification type" that should be easy enough

**Comment by SQLDBAWithABeard** [comment]
I like the idea of doing this but I'm going to close this issue for now. I think we should handle any resulting action on the output of the checks via seperate commands rather than within dbachecks - If need be we can have an additional module dbachecks-actions forexample
