### ISSUE TITLE
Report details inaccessible when emailed

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbachecks#309]
Using Outlook for testing (though I presume this is an issue in general) I can view the summary page as HTML in the body, but the link to the detailed summary of the tests doesn't work since the file doesn't exist.

Simplest approach would be to attach the HTML files to the email by default. Quick implementation of this is here: https://github.com/LowlyDBA/dbachecks/commit/f7d385b2fc056d4874596e5cafe98b113b4a23f6 . If ya'll like this approach I will open a pull request.

**Comment by potatoqualitee** [comment]
I do like that approach! But did I miss the part where it's attached? Please do attach the HTML, I think that's a solid solution until we work on more advanced emailing solution.

**Comment by LowlyDBA** [comment]
Line 244 piggybacks on $Attachments which already contains the .xml files

**Comment by potatoqualitee** [comment]
Excellent! Please PR
