### ISSUE TITLE
"Database Mail Profile" check looking for non-existent property?

### ISSUE THREAD

**Issue by tootblan** [sqlcollaborative/dbachecks#317]
[Line 56 of Agents.Tests.ps1](https://github.com/sqlcollaborative/dbachecks/blob/master/checks/Agent.Tests.ps1#L56) is looking for a property that does not exist on my servers. Tested against SQL 2012, 2014, and 2016. 

`(Connect-DbaInstance -SqlInstance $psitem).JobServer.AlertSystem.DatabaseMailProfile` is referencing the "DatabaseMailProfile" property of the SMO `Microsoft.SqlServer.Management.Smo.Agent.AlertSystem`, but that doesn't appear to exist:

![image](https://user-images.githubusercontent.com/25352226/36679015-d0a32904-1ad7-11e8-8cfc-469ec7f17421.png)

**Comment by potatoqualitee** [comment]
Thanks toot!
