### ISSUE TITLE
defaultbackupcompreesion is misspelled

### ISSUE THREAD

**Issue by ashdar** [sqlcollaborative/dbachecks#321]
The configuration item is spelled this way:
policy.backup.defaultbackupcompreesion 

The item should be spelled this way, with doubled "ss" and not doubled "ee":
policy.backup.defaultbackupcompression

**Comment by potatoqualitee** [comment]
Thanks so much! Will fix this asap unless you would like to submit the PR

**Comment by ashdar** [comment]
I'm sure that someone will fix this before I can get set up for summiting a
PR. Been meaning to get set up to submit to dbatools for ages, never done a
pull request, etcetera and so forth. Never seem to have time...

**Comment by potatoqualitee** [comment]
okie dok, np!

**Comment by potatoqualitee** [comment]
fixed in 1.0.3 👍
