### ISSUE TITLE
.ForEach() enumeration fails on PowerShell 4 with single instances

### ISSUE THREAD

**Issue by FriedrichWeinmann** [sqlcollaborative/dbachecks#327]
# Introduction
Starting PowerShell 4, you can efficiently enumerate collections by using the automatic `.ForEach()` method, which dbachecks uses.

*HOWEVER*

 - In PS4, this only exists for collections, not single items
 - Starting PS5, it automatically turns a single object into a collection, causing this to work

# Consequence

dbachecks is currently not compatible with PS4, since it uses the notation on single items (notably isntances) also.

# Proof of issue:
Run this on both PS4 & PS5:
```powershell
$item = 42
$item.ForEach({ $_ })
```
# Workaround / Solution
Run this on both PS4 & PS5:
```powershell
$item = 42
@($item).ForEach({ $_ })

$item2 = 23,42
@($item2).ForEach({ $_ })
```

**Comment by FriedrichWeinmann** [comment]
A little research using my favorite `PSModuleDevelopment` command (`find`):

```powershell
PS C:\> (find -Path F:\Code\Github\dbachecks -Pattern "\.ForEach" | measure).Count
144
PS C:\> (find -Path F:\Code\Github\dbachecks -Pattern " \(Get-SqlInstance\)\.ForEach" | measure).Count
59
PS C:\> (find -Path F:\Code\Github\dbachecks -Pattern " \(Get-ComputerName\)\.ForEach" | measure).Count
7
```
Meaning we have:

 - 144 Instances of use
 - 66 Instances that can be bulk updated
 - 78 Instances that need to be verified and potentially fixed manually

**Comment by potatoqualitee** [comment]
We addressed this by always returning an array - have you encountered issues that you can see?

**Comment by FriedrichWeinmann** [comment]
Haven't looked at the life version - my pre-release repo was enough to dig to the root cause based on the error message users were reporting.
Basically, at one point it's having a hiccup on an DbaInstance object

**Comment by ClaudioESSilva** [comment]
I was about to ask the same.

**Comment by FriedrichWeinmann** [comment]
`C:\Program Files\WindowsPowerShell\Modules\dbachecks\checks\Agent.Tests.ps1: line 63`

**Comment by ClaudioESSilva** [comment]
This was the fix (that Chrissy did) when I first spot it https://github.com/sqlcollaborative/dbachecks/blob/master/internal/functions/Get-SqlInstance.ps1#L11

**Comment by SQLDBAWithABeard** [comment]
Yes - a case of going through and having a look - I too thought we had caught all of these
