### ISSUE TITLE
Network latency reports instance name instead of server name

### ISSUE THREAD

**Issue by sqlhacker** [sqlcollaborative/dbachecks#331]
In the PowerBI report generated by dbachecks, the network latency check reports the instance name only, not the server name. So, if the instance is default, it only shows MSSQLSERVER or the named instance name. So, if running dbachecks on several instances which all happen to be default instances, there is no way to distinguish between the instances.

**Comment by SQLDBAWithABeard** [comment]
Fixed with #336
