### ISSUE TITLE
checkdb test reports passed and failed as same

### ISSUE THREAD

**Issue by TheRockStarDBA** [sqlcollaborative/dbachecks#340]
Run Invoke-DbcCheck -SqlInstance serverName -check LastGoodCheckDb

I have 11 databases that do not have LastGoodCheckDb.

Results:
Tests Passed: 11, Failed: 11, Skipped: 0, Pending: 0, Inconclusive: 0 

Expected Results : 
Tests Passed:0, Failed: 11

**Comment by js0505** [comment]
Checking this out with version 1.0.5 and I received a different error. What version are you running on?

**Comment by TheRockStarDBA** [comment]
with get-module .. I got 1.0.3 .. Do I have to update it ?

**Comment by js0505** [comment]
1.0.5 is now in the PowerShell Gallery

**Comment by js0505** [comment]
Well if you have PS 4 or lower it is going to fail as well, there is a known bug that I will try to get taken care of tonight.  My error relates to the PS4 bug and will see if it fixes yours.

**Comment by TheRockStarDBA** [comment]
I have ps4. When updating using `Update-Module dbachecks, dbatools, PSFramework, Pester` it still points to `C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.0.3\checks`

**Comment by js0505** [comment]
michalporeba is working on the PS4 fix now :). To get the latest you can do Find-Module dbachecks | Select-Object -ExpandProperty Version

Install-Module dbachecks -Force

**Comment by SQLDBAWithABeard** [comment]
Does this still happen with the latest version?

**Comment by TheRockStarDBA** [comment]
Will check on monday to confirm.

**Comment by TheRockStarDBA** [comment]
This is fixed. Thanks !
