### ISSUE TITLE
Write howto on installing PowerShellGet

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbachecks#343]

**Comment by wsmelton** [comment]
Done: https://docs.microsoft.com/en-us/powershell/gallery/psget/get_psget_module

**Comment by potatoqualitee** [comment]
that is beautiful, thanks @ashdar - gonna update the readme so will leave this open until i do

**Comment by TheRockStarDBA** [comment]
> That link is dead. How about this one?
> https://docs.microsoft.com/en-us/powershell/gallery/installing-psget

This link is dead too

**Comment by SQLDBAWithABeard** [comment]
closed with #820
