### ISSUE TITLE
Commands used in dbachecks must have tests in dbatools

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbachecks#344]
@wsmelton brought up a great point - not all commands used within dbachecks have Pester tests in dbatools. 

One of the requirements for dbatools getting to 1.0 is having at least one Pester test for each command. This task is primarily assigned to me. Shawn has offered to help. We would love help from any other test writer that is interested.

Ultimately, in dbatools, we should prioritize the commands used within dbachecks. And in the future, keep an eye out for any checks that use untested dbatools commands.

**Comment by jpomfret** [comment]
I can help on this quest also

**Comment by potatoqualitee** [comment]
Thank you so much Jess!

**Comment by jpomfret** [comment]
Did a quick bit of select-string & regex to get this list of Get-Dba commands from the dbachecks repo. Figured we could check them off we get them.

 - [ ] Get-DbaAgDatabase
 - [ ] Get-DbaAgentJob
 - [ ] Get-DbaAgentOperator
 - [ ] Get-DbaAgHadr
 - [ ] Get-DbaAgReplica
 - [ ] Get-DbaAvailabilityGroup
 - [ ] Get-DbaCmObject
 - [ ] Get-DbaConfig
 - [ ] Get-DbaDatabase
 - [ ] Get-DbaDatabaseFile
 - [ ] Get-DbaDbRecoveryModel
 - [ ] Get-DbaDefaultPath
 - [ ] Get-DbaDiskSpace
 - [ ] Get-DbaDump
 - [ ] Get-DbaLastGoodCheckDb
 - [ ] Get-DbaLogin
 - [ ] Get-DbaOrphanUser
 - [ ] Get-DbaRegisteredServer
 - [ ] Get-DbaService
 - [ ] Get-DbaSnapshot
 - [ ] Get-DbaSpConfigure
 - [ ] Get-DbaSqlBuildReference
 - [ ] Get-DbaSqlModule
 - [ ] Get-DbaSqlService
 - [ ] Get-DbaSuspectPage
 - [ ] Get-DbaXESession
 - [ ] Get-SqlInstance

**Comment by potatoqualitee** [comment]
aw whaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaat!!! awesome!! you can remove get-sqlinstance from the list - it is an internal command to dbachecks. can you also check for Test-Dba?

thanks so much, this makes it much easier.

**Comment by jpomfret** [comment]
Sure can - I checked the one's that have at least 85% code coverage... how high do you want it?

**Comment by SQLDBAWithABeard** [comment]
So very good - thank you :-) I too will try to take a look at some of these

**Comment by wsmelton** [comment]
The AG commands will need to be stricken because we can't make test for those commands in dbatools (no option in Appveyor at this time).

**Comment by wsmelton** [comment]
That SPN command as well because domains don't exist in Appveyor so the SPN commands will fail...unless we just mock the object lookup and such but it won't be integration test.

**Comment by potatoqualitee** [comment]
yah, i got most of the ones that are possible except for the orphan one which will take more time.

**Comment by shaneis** [comment]
Sorry, just seeing this now. I'll help out as much as I can as well

**Comment by potatoqualitee** [comment]
hey @jpomfret - can you remove Get-DbaService Get-DbaSnapshot? both of those aren't actually used (they were examples in a text)

**Comment by shaneis** [comment]
If Get-DbaService and Get-DbaSnapshot are out, and the AG ones are out...do I dare say that this is done? 🤔

**Comment by potatoqualitee** [comment]
yah, tho i added some ag ones based on a mock and export-clixml from a real ag db 💃 💃 💃 

so once I get it PR'd, we're done! what upp
