### ISSUE TITLE
Invoke-DbcCheck Exception instead of ErrorRecor

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbachecks#345]
invoke-dbccheck line 97

`Stop-PSFFunction -Message "Failure" -Exception $_`

should be `Stop-PSFFunction -Message "Failure" -ErrorRecord $_`

**Comment by michalporeba** [comment]
The same problem was reported as #379 and I quickly made the change and pull request #380 not seeing the 'good first issue' tag.

**Comment by potatoqualitee** [comment]
Thanks much!
