### ISSUE TITLE
Collation test suggestion

### ISSUE THREAD

**Issue by PsPsam** [sqlcollaborative/dbachecks#351]
Hello

I have SQL servers where I have databases that are wrong collation for many different reasons. I suggest that the test for collation to be changed to something like below. 

The change would mean to add a setting that you can define. I call it here WrongCollation. Then instead of doing a foreach loop of the databases and testing each database I test the attribute IsEqual in the result and count the result of false. This way I can define how many databases I have that is in the wrong collation for the database. Might be other ways to do this but this is how I solved it for me in my pester script that I have. 

```
Describe "Database Collation" -Tags DatabaseCollation, $filename {
    $WrongCollation = Get-DbcConfigValue policy.database.WrongCollation
    (Get-SqlInstance).ForEach{
        Context "Testing database collation on $psitem" {
            $count = (Test-DbaDatabaseCollation -SqlInstance $psitem -ExcludeDatabase Reportingpsitem, ReportingpsitemTempDB | Where-Object IsEqual -like $false).isequal.count
            if ($count -ne 0) {
                It "database collation should match server collation ($($psitem.ServerCollation)) on $($psitem.SqlInstance)" {
                    $count | Should -be $WrongCollation -Because "You have stated that you have $WrongCollation databses with the wrong Collation on the psitem, that can get collation conflict errors in tempdb"
                }
            } else {
                It "database collation should match server collation ($($psitem.ServerCollation)) on $($psitem.SqlInstance)" {
                    $count | Should -Be $WrongCollation -Because 'You will get collation conflict errors in tempdb'
                }
            }
        }
    }
}
```

I'm not sure how to add the ConfigValue so that I could test this localy, and I haven't had the time to look at it :) but I will.

/Peter

**Comment by SQLDBAWithABeard** [comment]
Is having a count of databases better than defining the database names?

**Comment by PsPsam** [comment]
Having the name instead would mean a better documentation of the server. So that would be better. I hadn't thought of that in my tests.

So no the count isn't better then defining the database name!

**Comment by SQLDBAWithABeard** [comment]
Are you happy to start to code the solution @PsPsam ? Feel free to ask questions in slack or on here and follow the coding guidelines :-)

**Comment by PsPsam** [comment]
I will try!

**Comment by SQLDBAWithABeard** [comment]
:-) That would be brilliant. Thank You :-)

**Comment by PsPsam** [comment]
https://github.com/sqlcollaborative/dbachecks/pull/372

The very very first pull request I have done.... :)

**Comment by SQLDBAWithABeard** [comment]
Thank you @PsPsam
