### ISSUE TITLE
dbachecks 1st time run fails with localhost not found.

### ISSUE THREAD

**Issue by PeterMTaylor** [sqlcollaborative/dbachecks#364]
G'Day,
I'm a noob with using SQL Server with Powershell (but am familiar with concepts of Pester) and will need some pointers to get my head around this ensure all test works with my current SQL Server configuration. I ran my first test as advised by https://sqldbawithabeard.com/2018/02/22/announcing-dbachecks-configurable-powershell-validation-for-your-sql-instances/

PS C:\Users\Peter\Source\Repos\Learn PS Error Handing> Invoke-DbcCheck -SqlInstance localhost -Check FailedJob
Executing all tests in '.' with Tags FailedJob

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\Agent.Tests.ps1

  Describing Failed Jobs

    Context Checking for failed enabled jobs on localhost
      [-] Error occurred in Context block 24.35s
        RuntimeException: Can't connect to localhost: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified 
        Exception: Can't connect to localhost: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the file specified 
        at Stop-Function, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.301\allcommands.ps1: line 88905
        at Get-DbaAgentJob<Process>, C:\Program Files\WindowsPowerShell\Modules\dbatools\0.9.301\allcommands.ps1: line 19490
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\Agent.Tests.ps1: line 65
        at DescribeImpl, C:\Program Files\WindowsPowerShell\Modules\Pester\4.3.1\Functions\Describe.ps1: line 161

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\Database.Tests.ps1

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\Domain.Tests.ps1

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\HADR.Tests.ps1

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\Instance.Tests.ps1

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\LogShipping.Tests.ps1

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\MaintenanceSolution.Tests.ps1

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.103\checks\Server.Tests.ps1
Tests completed in 24.35s
Tests Passed: 0, Failed: 1, Skipped: 0, Pending: 0, Inconclusive: 0 

Not sure how to resolve localhost setup.

Thanks,
Peter.

**Comment by SQLDBAWithABeard** [comment]
Hi Peter,

I imagine that your account does not have access to the SQL Server or that the MSSQLSERVER service is not running as that command works ok here

If you run Test-DbaConnection localhost what are your results?

**Comment by PeterMTaylor** [comment]
Thank you for taking my issue and responding quickly.
Pardon my delay in reply had to wait til back on my desktop at home after work.
I ran the command and came up with a warning confirming I haven't set up my localhost properly with my instance of SQLSERVER.
PS C:\Users\Peter\Source\Repos\Learn PS Error Handing> Test-DbaConnection localhost
WARNING: [Test-DbaConnection][21:40:50] Issue connection to SQL Server on localhost | Can't connect to localhost: System.ComponentModel.Win32Exception (0x80004005): The system cannot find the 
file specified 
Any suggestions next? Peter.

**Comment by potatoqualitee** [comment]
Hey @PeterMTaylor ! Please try running as administrator and let us know.

**Comment by PeterMTaylor** [comment]
Hi @potatoqualitee, please to me you.
I run all my Powershell ISE as administrator as a habit so the answer above is correct.

**Comment by PeterMTaylor** [comment]
Hi all,
I have played around the details of the  Invoke-DbcCheck -SqlInstance localhost -Check FailedJob and was able to understand that although I don't have a localhost installed as such but correctly worked the SQLinstance I'm after and all the tests turns green.
Thanks for your assistance and happy to close this issue.
