### ISSUE TITLE
Invoke-DbcCheck -check Future File Growth  Faild

### ISSUE THREAD

**Issue by Redwood001** [sqlcollaborative/dbachecks#375]
All test are failed with Future File Growth 

![image](https://user-images.githubusercontent.com/20565136/37111313-a281ef50-223f-11e8-8bac-5dd4dd0d7f57.png)

![image](https://user-images.githubusercontent.com/20565136/37114190-ef800b0e-2247-11e8-8834-1fe60bf5ab0d.png)

When you put $Threshold.vaule it should work fine.
Could you please change this in the master version?

DbaCheck Version: 1.1.0.4
DbaTools Version: 0.9.301
Windows Version 2012R2
Powershell Version 5.1

Thanks & Regards Redwood Dunken

**Comment by js0505** [comment]
I actually pushed a fix for this about 5 minutes ago to the dev branch. Can you pull that branch and test it out. Also, we are now on 1.1.06 as of today for dbachecks. That was about 3 hours ago.  Thank you!

**Comment by js0505** [comment]
crap

**Comment by js0505** [comment]
I actually pushed a fix for this about 5 minutes ago to the dev branch. Can you pull that branch and test it out. Also, we are now on 1.1.06 as of today for dbachecks. That was about 3 hours ago. Thank you!

**Comment by SQLDBAWithABeard** [comment]
PLease wait it is going through build now and will be in the gallery in 5 minutes or so :-)

**Comment by SQLDBAWithABeard** [comment]
1.1.107 will have this fix in

**Comment by Redwood001** [comment]
It works fine now.
Thanks for the update.

**Comment by js0505** [comment]
Awesome, thank you for confirming!
