### ISSUE TITLE
Code cleanup - Get-SqlInstance calls

### ISSUE THREAD

**Issue by michalporeba** [sqlcollaborative/dbachecks#381]
## Discussion

Since @potatoqualitee resolved the issue with `Get-SqlInstance` not always returning arrays (#365) should we clean up the code and remove the `@` from `@(Get-SqlInstance).ForEach {` ? 

while we are at it let's rename `Get-SqlInstance` to something that does not conflict with other module functions. I know it is internal, but it can be really annoying when you debug stuff, especially to start with, before you realise what's going on. 

How about we call it `Get-DbcSqlInstance`?

**Comment by michalporeba** [comment]
@SQLDBAWithABeard suggested calling it Get-DbcInstance in slack

**Comment by SQLDBAWithABeard** [comment]
I think this is a good idea

**Comment by potatoqualitee** [comment]
`Dbc` suggests to me an external command. I'd go with `Get-Instance`

**Comment by SQLDBAWithABeard** [comment]
I have put the function name change into this branch https://github.com/sqlcollaborative/dbachecks/tree/just-get-database-name

**Comment by potatoqualitee** [comment]
@wsmelton - i know you were having issues with it attempting to load. does that branch work for you?

**Comment by michalporeba** [comment]
I had problems with Get-SqlInstance too. The new Get-Instance works for me

**Comment by SQLDBAWithABeard** [comment]
Going to close this for now
