### ISSUE TITLE
ValidJobOwner update

### ISSUE THREAD

**Issue by js0505** [sqlcollaborative/dbachecks#391]
Bug fix: In regards to Valid Job Owner it currently reads `It "$($psitem.Name) owner $($psitem.OwnerLoginName) should be in this list $targetowner on $($psitem.Server)" {` I think it should read like this `It "Job $($psitem.Name)  - owner $($psitem.OwnerLoginName) should be $targetowner on $($psitem.SqlInstance)" {` thoughts? Also, the .Server does not populate so this needs to be updated anyways.

**Comment by SQLDBAWithABeard** [comment]
thank you @js0505 I will merge that with @frank687 PR for DB owners

**Comment by frank687** [comment]
@SQLDBAWithABeard  This can be closed. It's in 1.1.111
