### ISSUE TITLE
ValidDatabaseOwner check not working correctly 

### ISSUE THREAD

**Issue by peturgretars** [sqlcollaborative/dbachecks#392]
The dbacheck ValidDatabaseOwner should perform the validation based on the sid of the account and not the name. One of the best practice is to rename the sa user (hence your dbacheck "SaRenamed") and if that has been done then we will have failed status regardless if the owner is actually the original sa account. 

I think it should validate if the database owner has the sid 0x01 which I believe is always the sa account.

**Comment by SQLDBAWithABeard** [comment]
Which version of dbachecks are you using ?

The latest version has been altered to accept a group of possible job owner logins by name as the valid or invalid job owner will not necessarily be the sa account or the one with a sid of 0x01

**Comment by peturgretars** [comment]
I believe I upgraded yesterday or day before and the version is 1.1.109. 

PS C:\Windows\Temp\dbachecks> Get-Module Dbachecks -ListAvailable


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     1.1.109    dbachecks                           {Get-DbcConfig, Get-DbcConfigValue, Set-DbcConfig, Invoke-DbcCheck...}
Script     1.1.107    dbachecks                           {Get-DbcConfig, Get-DbcConfigValue, Set-DbcConfig, Invoke-DbcCheck...}

**Comment by peturgretars** [comment]
I just upgraded to 1.1.110 and it still reports invalid database owner when the owner is renamed sa user.

**Comment by SQLDBAWithABeard** [comment]
what is returned from  Get-DbcConfigValue agent.validjobowner.name ?

**Comment by SQLDBAWithABeard** [comment]
It is working as expected for me here

I wonder if you are not setting the expected name using

`Set-DbcConfig -Name policy.validdbowner.name -Value sarenamed`

![image](https://user-images.githubusercontent.com/6729780/37469505-54bbebb2-285d-11e8-8f1b-b40fb0e2ffb3.png)

and following a change of owner to the renamed sa account

![image](https://user-images.githubusercontent.com/6729780/37469692-c1879afc-285d-11e8-8747-9cbc443e7882.png)

**Comment by peturgretars** [comment]
You are absolutely right. I did not configure that, I just assumed it worked in similar way as the dbatools Test-DbaDatabaseOwner which I think recognizes if the sa has been renamed. 

But yes, when I have set it as you described above it works fine for me.

Thanks for the lesson and sorry for the inconvenience.

**Comment by SQLDBAWithABeard** [comment]
Never a problem :-)
