### ISSUE TITLE
TempDB Configurations - MaxSize on Logfiles 2TB vs. UNLIMITED

### ISSUE THREAD

**Issue by road42** [sqlcollaborative/dbachecks#393]
## Issue

I have an SQL Server with MaxSize in TempDB set to 2TB which is the maximal
filesize for a file. The TempDBConfiguration check failed in checking for
UNLIMITED.

`
   [-] should not have TempDB Files with MaxSize Set on HOST 33ms
        Expected $false, because Tempdb files should be able to grow, but got $true.
        62:                 $TempDBTest[4].CurrentSetting | Should -Be $TempDBTest[4].Recommended -Because 'Tempdb files should be able to grow'
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.110\checks\Instance.Tests.ps1: line 62
`

Once a MaxSize is set you cannot change the size back to UNLIMITED with ALTER DATABASE.

The check should check for UNLIMITED or 2TB.

### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? 
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5.1.1629.98
 - SQL Server (Edition|Version): 2014 Enterprise / 2016 Standard

### Steps to Reproduce
Set MaxSize on TempDB Logfile to 2TB. -> The check fails
MaxSize UNLIMITED on TempDB Logfile -> The check succeeds

## Feature Request

Make the check succeed on UNLIMITED and 2TB

**Comment by SQLDBAWithABeard** [comment]
Hi @road42 Thank you for this. 

I started looking at this this morning and realized that the check is working as expected as you have a tempdb file set to a value and the check is for it not to be set.

You can configure this by setting

Set-DbcConfig -Name  skip.tempdbfilesizemax -Value True

This will not run the check for the Max File Set

Note - you will need to update to the latest version 1.1.116 to do this as the config name was incorrect!

**Comment by SQLDBAWithABeard** [comment]
closed
