### ISSUE TITLE
Skip Databases that are secondary during Last Full Backup Check

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbachecks#396]
## Feature Request
The last full backup check doesn't account for a database's AG role, so a secondary may never or rarely have full backups in its server's msdb. This creates a lot of false flags. 
  
Current check: 
```PowerShell
            @(Get-DbaDatabase -SqlInstance $psitem -ExcludeDatabase tempdb | Where-Object {$_.CreateDate -lt (Get-Date).AddHours( - $graceperiod)}).ForEach{
                $offline = ($psitem.Status -match "Offline")
                It -Skip:$offline "$($psitem.Name) full backups on $($psitem.SqlInstance) Should Be less than $maxfull days" {
                    $psitem.LastFullBackup | Should -BeGreaterThan (Get-Date).AddDays( - ($maxfull)) -Because 'Taking regular backups is extraordinarily important'
                }
            }
```

Hacky stab at initial idea (not exact copy of the current one) that feels too heavy:
```PowerShell
           @(Get-DbaDatabase -SqlInstance $psitem  -NoFullBackupSince $lastBackupWindow -RecoveryModel Full).ForEach{
            $agname = Get-DbaAgDatabase -SqlInstance $psitem.SqlInstance -Database $psitem.Name 
            $role = Get-DbaAgReplica -SqlInstance $psitem.SqlInstance -AvailabilityGroup $agname.AvailabilityGroup.Name -Replica $psitem.SqlInstance | % role
            $secondary = ($role -match "Secondary")
                It -Skip:$secondary "$($psitem.Name) has been backed up between now and $lastBackupWindow on $($psitem.SqlInstance)" {
                    $psitem.LastFullBackup | Should -BeGreaterThan $lastBackupWindow -Because "we must backup our data"
                }
            }
```

You could also check that the primary node is being backed up, but I feel like that may be going down a road of complexity that isn't worth it when there are > 2 nodes that are being potentially rotated.

**Comment by wsmelton** [comment]
This would have to depend on the AG backup preference. That would determine right off if the replica could even have backups taken. So you might wrap that in a check to see if the backup preference is not set to primary only. You can go into the weights and all that are configured but I'd say that may be overkill for a simple check.

**Comment by LowlyDBA** [comment]
Yeah that's true - the rabbit hole could get pretty out of scope for the nature of these checks. I'll close for now unless I can figure out something more elegant/simple.

**Comment by LowlyDBA** [comment]
@wsmelton What about offloading the complexity as a config setting?

```powershell
Describe "Last Full Backup Times" -Tags LastBackup, Backup, DISA, $filename {
    $maxfull = Get-DbcConfigValue policy.backup.fullmaxdays
    $graceperiod = Get-DbcConfigValue policy.backup.newdbgraceperiod
    $skipreadonly = Get-DbcConfigValue skip.backup.readonly
    $skipAGsecondary = Get-DbcConfigValue skip.backup.agsecondary
    @(Get-Instance).ForEach{
        Context "Testing last full backups on $psitem" {
            @((Connect-DbaInstance -SqlInstance $psitem).Databases.Where{ ($psitem.Name -ne 'tempdb') -and $Psitem.CreateDate -lt (Get-Date).AddHours( - $graceperiod) -and ($ExcludedDatabases -notcontains $PsItem.Name)}).ForEach{ 
                if ($skipAGsecondary -eq $true) {$isAGSecondary = $psitem.AvailabilityGroupName -and (Get-DbaAgReplica -SqlInstance $psitem.Parent.Name -AvailabilityGroup $psitem.AvailabilityGroupName -Replica $psitem.Parent.Name).Role -eq "Secondary"}
                $skip = ($psitem.Status -match "Offline") -or ($psitem.IsAccessible -eq $false)  -or ($psitem.Readonly -eq $true -and $skipreadonly -eq $true) -or ($isAGSecondary -eq $true -and $skipAGsecondary -eq $true)
                It -Skip:$skip "$($psitem.Name) full backups on $($psitem.Parent.Name) Should Be less than $maxfull days" {
                    $psitem.LastBackupDate | Should -BeGreaterThan (Get-Date).AddDays( - ($maxfull)) -Because "Taking regular backups is extraordinarily important"
```

I believe it is a common enough scenario to be only taking full backups on a primary node that isn't expected to swap very often and not caring about the possibility of `COPY_ONLY` full backups on a secondary node.

**Comment by wsmelton** [comment]
I don't believe a primary only backup is a common scenario at all. I have only touched two environments so far that were doing primary only preference and that was just because they did not want to pay for licenses on all the secondaries. 

I will leave it up to @SQLDBAWithABeard on how he wants to handle it in the checks.

If you only got 400-500ms that will be unique as well. Is that from having 3+ replicas with only two on site and the rest over a WAN link to an offsite DR location? Environments where the AG involved DR sites I would be shocked if I got that timing.

I'm hoping by next month my workload will go done (transitioning to a new position) and I will start working on many more commands in dbatools around AG configurations and information like backups.

Ref: sqlcollaborative/dbatools#1712

**Comment by LowlyDBA** [comment]
It might be the Friday talking, but how is it not common to do full backups on the primary node? I imagine any normal production server would necessitate taking full backups from the primary in order to have proper restore options via keeping transactional consistencies across full/tran/diff backups, whereas doing a `COPY_ONLY` full backup from a secondary would leave you with scary odds of achieving any reasonable RPO.

**Comment by LowlyDBA** [comment]
Yes, you can do fulls, [but only as `COPY_ONLY` backups](https://docs.microsoft.com/en-us/sql/database-engine/availability-groups/windows/active-secondaries-backup-on-secondary-replicas-always-on-availability-groups?view=sql-server-2017#SupportedBuTypes) that will not allow for a reset on your differential backup size. Diff backups are fairly common and if you're using them you want to *eventually* have a full backup on a primary instance that isn't  restricted to`COPY_ONLY`, otherwise you'll be getting diffs that increase continually. 

I guess if you only need tlog and full backups that works fine, but most production systems I've worked with recently need diffs thrown in the mix.

**Comment by wsmelton** [comment]
Again up to beard on what he wants.

**Comment by wsmelton** [comment]
Everyone is going to have a "common" configuration of how things work. An argument can be made both directions as to when and why you would never use differential backups in an Availability Group configuration/setup. (Primary being it defaults the purpose of being able to offload your backups to a secondary and not effect production workloads.).

To say "rare" when it comes to full backups on the secondary though, is of personal opinion and not proven as a standard. So at most I would agree with potential to make it into a configuration item for the check. You could just as easily have a single configuration of `IgnoreAGReplicas` or `IgnoreAGSecondaries`.

If I recall the primary reason this check even touches the secondaries is you are not aware of failovers when you are validating backups. If a failover occurred a differential could have also been taken on that secondary replica, if the backups jobs are configured properly. Simply to point that there are many variations of how backups are configured in the wild for Availability Groups.
