### ISSUE TITLE
Proposal: Invoke-DbcFailureResponse

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbachecks#405]
`Invoke-DbcCheck -SqlInstance sql2017 -Check LastGoodCheckDb -PassThru -EnableFix | Invoke-DbcFailureResponse`

The `-EnableFix` will add two or three properties to output (which makes it slower) hence the requirement of a new switch. `Server` which is the SMO connected object $server then `FixType` and `FixTarget`

```powershell
foreach ($failure in ($InputObject.TestResult | Where-Object Result -eq Failed)) {
    $target = $failure.FixTarget
    $server = $failure.Server
    switch ($failure.Describe) {
        "Last Good DBCC CHECKDB" {
            $server.Query("DBCC CHECKDB $target")
        }
        "Recovery Model" {
            $recoverymodel = Get-DbcConfigValue -Name policy.recoverymodel.type
            Set-DbaDbRecoveryModel -SqlInstance $server -Database $target -RecoveryModel $recoverymodel 
        }
    }
}
```

We can add `-Confirm:$false` to all of them or let the user decide perhaps with a config. I'm proposing this but don't currently have plans to program it so if it's agreed on, anyone who wants can grab it. Just wanted to throw it out there as a potential solution for a question we regularly get.

FixType would be something like Database or Instance. Not sure if it'd be needed but seems like it'd have the potential to be useful.

**Comment by shaneis** [comment]
Ooooh are we talking something like 
```
....
"Last Full Backup" {
    $Backup = Get-DbcConfigValue -Name policy.backup.maxfulldays
    Backup-DbaDatabase ...
}
```
???

**Comment by potatoqualitee** [comment]
Yep! So whatever we would do to fix it but instead, PowerShell fixes it.

**Comment by wsmelton** [comment]
So adding a remediation button? (aka gold disk lock it all down 🎉 🎈 👶 )

**Comment by SQLDBAWithABeard** [comment]
I am closing this as well because there has been no requests for a couple years - If I am wrong let me know
