### ISSUE TITLE
All Diff Backup pester test are failed

### ISSUE THREAD

**Issue by Redwood001** [sqlcollaborative/dbachecks#410]
## Issue

This is a bug or unexpected behaviour/feature request/new check/question (delete as applicable)

### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? 

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`

![image](https://user-images.githubusercontent.com/6729780/37113488-60e5e172-21fa-11e8-8115-814edfbfabb6.png)

- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2012R2
 - PowerShell Version: 5.5.1
 - SQL Server (Edition|Version): SQL Server Enterprise 2016 SP1 CU8 
 - DbaTools version:  0.9.306

### Steps to Reproduce

 All results from this test are failed. I am sure all the backups are present

$Checks = (
    'LastDiffBackup'
)
invoke-DbcCheck -Check $Checks  

When I change the markt line in LastDifferentialBackupDate intead of LastDiffBackup it runs fine

![image](https://user-images.githubusercontent.com/20565136/37715823-4c3eb8e2-2d1d-11e8-9cc9-5508627a1277.png)

This also applies to the full backup test

 - [x] Attach any screenshots (if possible/allowed)
 - [ ] Attach output from PowerShell console (if possible/allowed)

**Comment by jhoudi** [comment]
Correct, the same counts for LastFullBackup and LastLogBackup. All checks are using wrong properties from SMO.

I can reproduce it on the newest version 1.1.113
