### ISSUE TITLE
ValidJobOwner Checks For MSX Jobs

### ISSUE THREAD

**Issue by daniel-merchant** [sqlcollaborative/dbachecks#414]
Testing Valid Job Owner fails on jobs from MSX multi-server jobs as these do not report an owner.
Perhaps these types of job should be excluded from the standard checks.

### Steps to Reproduce
Create a multi-server SQL agent job and run check for ValidJobOwner:
Invoke-DbcCheck -Check ValidJobOwner

Check will always fail for the multi-server job.

## Feature Request
Exclude agent owner tests for jobs where Get-DbaAgentJob SqlInstance.
MSX jobs should be identifiable where the OriginatingServer does not equal the SqlInstance.
e.g.

```
@(Get-DbaAgentJob -SqlInstance $psitem -EnableException:$false).ForEach{
if ($AgentJob.SqlInstance -eq $AgentJob.OriginatingServer)
{Run Check}
else
{Do not run check}    
}
```

Alternatively could raise this in the DBATools Test-DBAJobowner function to take into account MSX jobs if that makes more sense?

**Comment by SQLDBAWithABeard** [comment]
@daniel-merchant Thank you so much - Please can you open an issue on dbatools for this 

https://github.com/sqlcollaborative/dbatools/issues

as that is the command that we use. I would rather it was fixed for everyone rather than just dbachecks
