### ISSUE TITLE
Add support to be able to use Register-PSFConfig and set the -Scope

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbachecks#426]
## Feature Request
Issue created after discussion on slack channel, would be nice to have a way of setting config values for any user on a machine. One use case would be for running scheduled jobs that use dbachecks under other accounts.

**Comment by FriedrichWeinmann** [comment]
Sounds reasonable to me.

Implementation recommendation:

 - On `Import-DbcConfig` and `Set-DbcConfig` add a switch parameter named `-System` (or maybe `-AllUsers`)
 - If this switch is set, call `Register-PSFConfig` with the `-Scope SystemDefault` parameter

**Comment by michalporeba** [comment]
I think the switch should be also added on read, so one can decide if local user configuration should be used, or the global one, probably needs to be added to to `Invoke-DbcCheck` and `Get-DbcConfig`

**Comment by FriedrichWeinmann** [comment]
Actually, that's not a supported scenario @michalporeba , sorry.
System beats user where registry-persistence is concerned (and the values are retrieved on `PSFramework` import, not when `dbachecks` loads).

**Comment by michalporeba** [comment]
Then I don't like it as much as I thought I would. Does it mean that if you once register system value then it effecitvely always overwrites the values for all of the users?

**Comment by FriedrichWeinmann** [comment]
Heya @michalporeba you are right and it does not make much sense this way around. Changing it however would be a somewhat breaking change. I strongly try to avoid those, but this looks like a justified cause for such a change.

I've filed an issue on the project's page:

https://github.com/PowershellFrameworkCollective/psframework/issues/89

This should give other interested parties the option to weigh in and consider the implications.

If I haven't heard a reasonable argument _against_ correcting this, I will implement it.

**Comment by FriedrichWeinmann** [comment]
Heya, just wanted to update on a recent change:
Updated the configuration from registry precedence as discussed:
```
All users (enforced) > Per user (enforced) > Per user (default) > All users (default)
```
Global rules can thus still be enforced, but user defaults beat system defaults
