### ISSUE TITLE
Let's make custom check repositories feel more at home

### ISSUE THREAD

**Issue by michalporeba** [sqlcollaborative/dbachecks#436]
### it's just an idea 
Currently it is possible to develop custom checks and place them in a folder which is then 'registered' by setting the `app.checkrepos` configuration variable and included by `Invoke-DbcCheck` when executing checks. Most commands will not work with custom checks as they are not in `checks.json`. 

How about we make them more at home and include them in the whole process? I've got a few ideas how it could be done

We have the unit tests file which we use to validate our checks. When a new file  (or changed file) is discovered in a custom check repository we could unit test it and if it passes treat it as if it was ours, include it in `checks.json`, show it in Get-DbcCheck output. If it doesn't pass the tests don't include it, simply display a warning message that it failed, point to a link, suggest improvements, but run it similarily to how it is done now. 

This will ensure that external custom checks don't have tags that conflict with the existing ones, that they descriptions are good enough to be used in PowerBI report.

We could keep a list of known files with their last modifed dates to quickly see if a custom file has been already processed or not. 

The custom checks should be included in Get-DbcCheck. We could add a property IsDefault, or IsCustom

We could _pre-process_ those custom checks too, if we wanted, or make some extra unit tests for them to make sure they follow rules we set out. To make it clear that the check is not supported one, all the descriptions could start with `CUSTOM CHECK `

It might be a step too far (but I don't think it is completely mad, so please hear me out)... it wouldn't be too difficult to have custom checks that can 'override' or rather replace individual checks. That would allow peopel with special needs (and skills) to be able to modify one (or a few) specific checks (by tag) to diverge from what works for most and keep their own custom version while still update the module without worry of it being overwritten. We could use it perhaps to users with older SQL versions as a way?

**Comment by SQLDBAWithABeard** [comment]
As long as the custom checks are tagged correctly then the commands are working for me here
