### ISSUE TITLE
Option to execute only checks that failed in the previous run

### ISSUE THREAD

**Issue by michalporeba** [sqlcollaborative/dbachecks#437]
### it is just an idea
How about adding an option to `Invoke-DbcCheck` that would invoke only the checks that failed during the last run? The use case would be working on fixing something the checks have identified, and trying to make sure that it is really fixed. 

At the moment it would be fairly easy to implement using the tags, but that does not solve problems with checks like the new HADR, where all of the checks are done under single tag. Perhaps it would be worth thinking about how we could skip items on `It` level too?

**Comment by SQLDBAWithABeard** [comment]
I dont think this is a realistic option right now
