### ISSUE TITLE
PBI: Auto-sort Matrix by Failed desc

### ISSUE THREAD

**Issue by hfleitas** [sqlcollaborative/dbachecks#442]
## Issue

This is a feature request.

## Feature Request
   
By default, order the matrix by Failed desc. It would be helpful to see those red high count items right at the top.

I clicked the Data tab, and it's doing it by Result. Failed is a Measure. Perhaps, editing the query it could then be returned as a column...not sure yet.  

Thx,
Hiram

**Comment by SQLDBAWithABeard** [comment]
Thats a great idea - paging @ClaudioESSilva :-)

**Comment by ClaudioESSilva** [comment]
Hi @hfleitas 

Done https://github.com/sqlcollaborative/dbachecks/pull/459 😃 

Give it a try and let us know if it's ok.

**Comment by SQLDBAWithABeard** [comment]
merged

**Comment by hfleitas** [comment]
@ClaudioESSilva , I tried it out. Thx a lot, works well. :))
