### ISSUE TITLE
Get-DbcCheck description improvements

### ISSUE THREAD

**Issue by NickGuy1** [sqlcollaborative/dbachecks#444]
## Issue

In many cases the description output from Get-DbcCheck does not provide much detail in addition to the unique tag name and does not highlight which config settings would be required for the specific check

## Feature Request
   
Can the description output from Get-DbcCheck be enhanced to show more details about what would be checked and which config settings would relate to this

For example UniqueTag "ValidDatabaseOwner" currently shows a description of "Valid Database Owner" it would be good to have a bit more detail about this such as
 "checks the databases (excluding policy.validdbowner.excludedb) owner is valid based on  policy.ValiddbOwner.Name and/ or policy.invaliddbowner.name"

**Comment by SQLDBAWithABeard** [comment]
This is an awesome suggestion and will help people who are first starting with dbachecks - Thank you

**Comment by SQLDBAWithABeard** [comment]
I think this is two things.

Your brilliant idea which could be an additional property retrieved with Get-DbcCheck - so yes please @michalporeba 

and also an improvement to the description of the checks in the commands which should be hard coded

**Comment by michalporeba** [comment]
So let's keep this issue to the description improvement. The collection of config values I will do. The issue for that is #450

**Comment by SQLDBAWithABeard** [comment]
Updated descriptions added
