### ISSUE TITLE
HADR Check - ASync IsFailoverReady should be False

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbachecks#445]
`                        It "Database $($psitem.DatabaseName) should be failover ready on the secondary replica $($psitem.Replica)" {
                            $psitem.IsFailoverReady | Should -BeFalse -Because 'The database on the asynchronous secondary replica should be ready for manual failover'
`

This check  Should -BeFalse since an Async node can never be in a synchronized state.

**Comment by SQLDBAWithABeard** [comment]
fixed in 1.1.120 - with ea56f91f025a4b854b2b4bf1903de5cbea3ff3bc - Thank you @gbargsley
