### ISSUE TITLE
HADR Check - Somehow omit offline IP's in multi-subnet configuration

### ISSUE THREAD

**Issue by gbargsley** [sqlcollaborative/dbachecks#446]
When you have a multi-subnet cluster configured there is an IP assigned to the cluster for both subnets.  However, only the active subnet will have the IP resource online.  The other IP resource will be offline.  This is causing a test to fail and would be nice if it could be skipped or somehow not show test to fail.

@SQLDBAWithABeard 
one of those means resources where resourcetype IP Address where ownergroup -eq AGNAme

**Comment by SQLDBAWithABeard** [comment]
@gbargsley can you try this branch please https://github.com/sqlcollaborative/dbachecks/tree/HADR-multi-subnet

**Comment by gbargsley** [comment]
Looks like it is just checking that at least one IP is online.  Is that what you were going for? It works for me.
![image](https://user-images.githubusercontent.com/169602/38680850-ef7ee890-3e2c-11e8-82a8-5e8b430c5eb0.png)

**Comment by SQLDBAWithABeard** [comment]
Thats what I aimed for. Is that what is required?

**Comment by gbargsley** [comment]
Perfect for me. I cannot failover to my other subnet to test. But if you are checking for one active ip I think that covers a good test.
