### ISSUE TITLE
Get-DbaOrphanUser only returns a single row per database

### ISSUE THREAD

**Issue by GarthAurish** [sqlcollaborative/dbachecks#451]
## Issue
Get-DbaOrphanUser only returns a single row per database.  So if a single DB has multiple orphan users then it only counts as 1.  Question is whether this should return the full count of orphans per DB by returning @($results.user).count instead of @($results).count

### General Troubleshooting steps
- Checked latest version of Database.Tests.ps1 file has the same return value.
- Manually ran the command to show that the object can produce the exact number of orphan users per DB

### Version Information
Although code reacts the same on multiple versions of SQL Server
 - Windows 10
 - PowerShell Version: 5.1
 - SQL Server SQL Server 2008

### Steps to Reproduce
<--  
PS C:\Users\userID> $results = Get-DbaOrphanUser -SqlInstance tst-sqlserver.domain.com

PS C:\Users\userID> $results

SqlInstance              DatabaseName   User                            
-----------              ------------   ----                            
tst-sqlserver.domain.com DB1        {user1, user2, user3, user4...}
tst-sqlserver.domain.com DB2          user1
tst-sqlserver.domain.com DB3        {user1, user2, user3, user4...}

PS C:\Users\userID> @($results).count
3

PS C:\Users\userID> @($results.user).count
32

## Feature Request
I would like it to return the full number of orphan users rather than just the number of databases with orphan users

**Comment by SQLDBAWithABeard** [comment]
Hi @GarthAurish

Thank you for creating this. Is this an issue for you with the results of the dbachecks pester test or the dbatools command?

**Comment by GarthAurish** [comment]
The dbatools command.  Whoops logged it under the wrong area.  Would you like me to log this issue directly under the dbatools command

**Comment by SQLDBAWithABeard** [comment]
Yes please, if I close this one, can you raise an issue in dbatools please :-)
https://github.com/sqlcollaborative/dbatools/issues
