### ISSUE TITLE
invoke-dbccheck -check HADR complains about failover clusters module when run from local workstation

### ISSUE THREAD

**Issue by TheRockStarDBA** [sqlcollaborative/dbachecks#452]
## Issue

This is a  unexpected behavior 

### General Troubleshooting steps
- [ ] Verified running the latest release of dbachecks? 

Invoke-DbcCheck -Check HADR -ComputerName

Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.121\checks\HADR.Tests.ps1
WARNING: [09:55:48][HADR.Tests.ps1] FailoverClusters module could not load - Please install the Failover Cluster module using Windows Features  | The specified module 'FailoverClusters' was not loaded because no valid module file was found in any module directory.

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`

TRUE

- [ ] Verified errors are not related to permissions?
- [ ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

 
 Ideally, from a central admin server, failover cluster module is not installed. The command should perform HADR check on the remote specified computer or sql instance.

**Comment by wsmelton** [comment]
Why can you not install the failover cluster module on the central server? It is simply client tools just like the server administrator console or AD tools.

**Comment by TheRockStarDBA** [comment]
I can install but we have different domains and for some domains, I need the ability to run the tests from my local windows 7 PC. Other domains, I can run the test from central server.

**Comment by SQLDBAWithABeard** [comment]
Unfortunately this is going to be a limitation of dbachecks. Running remote failover cluster commands brings unexpected behaviour.

Unless anyone has any ideas I am sorry we will have to close this without fixing
