### ISSUE TITLE
Agent checks - skip for express edition

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbachecks#455]
## Feature Request
Wonder if the agent checks should only fail if the SQL edition isn't Express.  I get failed agent checks for Express boxes where that is really the expected output.

![image](https://user-images.githubusercontent.com/981370/38946615-0151c620-4308-11e8-838b-99cda38b5f4e.png)

Checks affected:
- AgentServiceAccount
- FailsafeOperator
- DBAOperators - this gets an error in the context block
- DatabaseMailProfile
- FailedJob - kind of, there should just be syspolicy_purge_history

**Comment by jpomfret** [comment]
Hey @SQLDBAWithABeard, I missed your comment on this. It didn't fix it my issue because the edition returns this `Express Edition (64-bit)` . I opened PR #476 that should fix it.

**Comment by SQLDBAWithABeard** [comment]
Duh rat!!!
