### ISSUE TITLE
Exclude Read Only Databases

### ISSUE THREAD

**Issue by LPareigis** [sqlcollaborative/dbachecks#468]
I believe that this would be new functionality. In our environment if 10,000+ databases we do not back up databases that are set to read only.  At this point in time the -Check LastBackup. Does exclude offline databases.  Adding the ability to also exclude ReadOnly databases would be very helpful.   

Thank you in advance for this amazing tool.

**Comment by SQLDBAWithABeard** [comment]
I have added a configuration item skip.backup.readonly  to enable this
