### ISSUE TITLE
Ola Hallengren Checks not checking Retention correctly

### ISSUE THREAD

**Issue by joshcorr** [sqlcollaborative/dbachecks#470]
## Issue

When executing the MaintenanceSolution check it does not appear to be grabbing the retention time correctly. I just installed the latest Ola Hallengren solution with the following settings
```
SET @CreateJobs          = 'Y'          -- Specify whether jobs should be created.
SET @BackupDirectory     = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup' -- Specify the backup root directory.
SET @CleanupTime         = 250         -- Time in hours, after which backup files are deleted. If no time is specified, then no backup files are deleted.
SET @OutputFileDirectory = NULL         -- Specify the output file directory. If no directory is specified, then the SQL Server error log directory is used.
SET @LogToTable          = 'Y'          -- Log commands to a table.
```
The jobs created by default are not sqlcmd (as they use to be from my understanding). Now the jobs are T-SQL in the following format.
```
EXECUTE [dbo].[DatabaseBackup]
@Databases = 'SYSTEM_DATABASES',
@Directory = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Backup',
@BackupType = 'FULL',
@Verify = 'Y',
@CleanupTime = 250,
@CheckSum = 'Y',
@LogToTable = 'Y'
```
I didn't have time to dig further into it, but the problem may be in the in lines 62-79 of this check.

```
            if ($Retention) {
                Context "Checking the backup retention on $psitem" {
                    $jobsteps = $job.JobSteps | Where-Object { $_.SubSystem -eq "CmdExec" }
                    if ($jobsteps) {
                        $results = $jobsteps.Command.Split("@") | Where-Object { $_ -match "CleanupTime" }
                    }
                    else {
                        $results = $null    
                    }
                    
                    It "Is the backup retention set to at least $Retention hours" {
                        if ($results) {
                            $hours = $results.split("=")[1].split(",").split(" ")[1]
                        }
                        $hours | Should -BeGreaterOrEqual $Retention -Because 'The backup retention needs to be correct'
                    }
                }
            }
```

### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? 
         Yes, version 1.1.124
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10 | Pro
 - PowerShell Version: 5.1.16299.98
 - SQL Server (Edition|Version): Enterprise | 13.0.1708.0

### Steps to Reproduce
 - [x] Attach any screenshots (if possible/allowed)
![image](https://user-images.githubusercontent.com/13426972/39630576-b7656ddc-4f7d-11e8-84c8-ca919ba36dd7.png)
![image](https://user-images.githubusercontent.com/13426972/39630792-6c2c6036-4f7e-11e8-96e6-94b5e51c4f03.png)

**Comment by joshcorr** [comment]
Did find that the new jobs created by the Ola Maintenance Solution are using a different Job Subsystem.

![image](https://user-images.githubusercontent.com/13426972/39666508-b52faa6e-5072-11e8-8364-ec0b9de5cf95.png)

Looked on the [version history](https://ola.hallengren.com/versions.html) for the maintenance solution and this change happened on April 20, 2018

**Comment by SQLDBAWithABeard** [comment]
THANK YOU - Merged
