### ISSUE TITLE
Spelling

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#492]
### General Troubleshooting steps
- [X ] Verified running the latest release of dbachecks? 

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`

![image](https://user-images.githubusercontent.com/6729780/37113488-60e5e172-21fa-11e8-8115-814edfbfabb6.png)

- [X ] Verified errors are not related to permissions?
- [X ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Steps to Reproduce
Run Get-DBcCheck | OGV

Groan at spelling mistakes in descriptions

![image](https://user-images.githubusercontent.com/6729780/40719460-9f60cc70-640b-11e8-8648-6d4430a78eaa.png)

![image](https://user-images.githubusercontent.com/6729780/40719534-ccf57d5c-640b-11e8-88af-9f665078a174.png)

![image](https://user-images.githubusercontent.com/6729780/40719587-f194f368-640b-11e8-9cc3-ece63ba29d01.png)

![image](https://user-images.githubusercontent.com/6729780/40719625-1219594e-640c-11e8-88f1-30cdec0b06ff.png)

![image](https://user-images.githubusercontent.com/6729780/40719665-28876068-640c-11e8-8a0e-629571c4295e.png)

![image](https://user-images.githubusercontent.com/6729780/40719701-3ebc7ae4-640c-11e8-8ed7-312024d8d141.png)

**Comment by fatherjack** [comment]
I'm missing something - "GetDbcCheck | OGV" doesnt give me a Description column in the results. Can you confirm that is the best way to see the issues you are highlighting please?

**Comment by SQLDBAWithABeard** [comment]
Are you using the latest version? This should have been available for the last few releases.

**Comment by SQLDBAWithABeard** [comment]
fixed in latest release
