### ISSUE TITLE
Updating output

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbachecks#495]
### Question

The punctuation makes it hard for me to read in Power BI. For instance

"last good integrity check for XYZ Should Be less than"

I'd like to change that to "Last good integrity check for XYZ should be less than"

But I'm not sure if there are things depending on on the output being capitalized a certain way. Please let me know and I can update the tests.

**Comment by SQLDBAWithABeard** [comment]
Of course that can be altered. The only restrictions are the ones that were put in place in the beginning which are in the wiki. I don't know of any case-sensitive requirements that we check

Also, any restrictions for the Power Bi output can be caught by following these steps

https://github.com/sqlcollaborative/dbachecks/wiki/Running-Unit-Tests 

prior to submitting a PR.
