### ISSUE TITLE
Allow build check to use "MaxBehind" parameter from Test-DbaSqlBuild

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbachecks#499]
## Feature Request
   
*Enhancement*

Incorporate [Test-DbaSqlBuild](https://dbatools.io/functions/test-dbasqlbuild/) and add config values to support the `MaxBehind` parameter for the `SupportedBuild` check. Since this function also returns the support date it should be easy to start using that result set.

The current iteration checks for MS support dates but that isn't super useful for keeping servers up to most patching policies.

**Comment by LowlyDBA** [comment]
I have a rough homegrown version of this already and am happy to make a PR for the changes if ya'll are busy :)

**Comment by SQLDBAWithABeard** [comment]
That would be awesome @LowlyDBA 

Please follow the guidelines here

https://github.com/sqlcollaborative/dbachecks/wiki/Writing-a-New-Check 

and if you have any questions please shout

**Comment by LowlyDBA** [comment]
Sweet. I should be able to scrape a PR together next week. 👍
