### ISSUE TITLE
Add parameter for the configuration path

### ISSUE THREAD

**Issue by sanderstad** [sqlcollaborative/dbachecks#501]
## Feature Request
It would be nice to put in a parameter to set the configuration path.
That way the user can set the config path to point to GIT or any other part and import and export the settings accordingly

 
<-- Simply answer the question - What would you like dbachecks to do that it doesn't? -->   
   
### What should be configurable for the results of the check ?
    
<-- A value, a set of properties (like FULL, SIMPLE, BULKLOGGED) -->  
<-- Should there be any default values for the configs? -->   
    
### What should be able to be excluded from being tested ?
    
<-- Could be databases, Could be Availability Groups etc -->  
<-- This would not be instances -->

**Comment by SQLDBAWithABeard** [comment]
This functionality is already available with Import-DbcConfig

**Comment by potatoqualitee** [comment]
this is my request, i'll add it 😅
