### ISSUE TITLE
Custom filename for JSON file from Update-DbcPowerBiDataSource

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbachecks#504]
## Feature Request
   
When working with a longer custom list of checks (i.e. specifying individually rather than using all checks in a file) it is easy to generate a filename too long to be saved properly in Windows:

```
WARNING: [16:44:01][Update-DbcPowerBiDataSource] Failure | The specified path, 
file name, or both are too long. The fully qualified file name must be less 
than 260 characters, and the directory name must be less than 248 characters.
```
  
Being able to specify the target JSON file name would allow this to be avoided.

**Comment by LowlyDBA** [comment]
I know the alternative is to utilize the ExcludeCheck flag, but that ends up being unclear as to what you're actually trying to check in the command and would result in new checks being automatically added to your check cycle when you upgrade.

**Comment by SQLDBAWithABeard** [comment]
Hi @LowlyDBA - Sorry I missed this - You can already do this with the -Environment parameter on Update-DbcPowerBiDataFile (The hardest command name to say :-) )

(This code also creates naming convention for the XML for VSTS

Heres how I do this
``        $date = Get-Date -Format yyyMMddHHmmss
        $base =  $VMName + "_" + $System + "_" + $date
        $filename = "C:\windows\Temp\DbaStack\" + $base + "_" + "PesterResult.xml"
        $PesterResult = Invoke-DbcCheck -OutputFile $filename -OutPutFormat NUnitXml -PassThru 
        $PowerBiFileName = $System +"-" + $VMName+ "-" + $date
        $PesterResult | Update-DbcPowerBiDataSource -Environment $PowerBiFileName

![dbachecks](https://user-images.githubusercontent.com/6729780/43703378-8a888fa8-9954-11e8-86ae-4d1aba4f9e53.PNG)

**Comment by LowlyDBA** [comment]
@SQLDBAWithABeard  I updated to the latest version and it still seems to append all specific checks in the name. 

Using:

```PowerShell
Invoke-DbcCheck -Show Summary -SqlInstance $array -Check $envChecks -PassThru -OutputFormat NUnitXml | Update-DbcPowerBiDataSource -Environment $ConfigurationGroup -Path $destPath -Append
```
Results in:
![image](https://user-images.githubusercontent.com/16843041/43731841-cdfce936-997d-11e8-9590-8908ffef7bb1.png)

Where $configurationGroup is either "prod" or "staging" and despite the `-Append` flag, we are deleting the files before each run of the script.

**Comment by SQLDBAWithABeard** [comment]
Don’t use the path parameter. Specify the entire path in the environment parameter instead

**Comment by LowlyDBA** [comment]
Thank you!

**Comment by LowlyDBA** [comment]
Still struggling with this...I think the issue is still that the code appends the checks/tags *in addition to* the environment name versus *instead of*:

```
$basename = "dbachecks_$i"
        if ($InputObject.TagFilter) {
            $basename = "$basename`_$($InputObject.TagFilter -join "_")"
        }
        
        if ($Environment) {
            $basename = "$basename`_$Environment"
        }
```

So you still get `dbachecks_1_check1_check2_check3_check99_environment.json` as a name as soon as you specify `-Check` or `-Tag`

**Comment by SQLDBAWithABeard** [comment]
of course, I didnt use a checks param - apologies

Let me look at this now.
