### ISSUE TITLE
ExcludeDB

### ISSUE THREAD

**Issue by derekjohnston** [sqlcollaborative/dbachecks#506]
## Bug Report
I set  config Set-DbcConfig -Name command.invokedbccheck.excludedatabases -value 'msdb'   and I run Invoke-DbcCheck -AllChecks  -Show Fails -PassThru | Update-DbcPowerBiDataSource -Environment Production  - but I am still getting an error that msdb has duplicate indexes??

### Version Information
 - Operating System (Name|Version): windows Server 2016 Standard
 - PowerShell Version: 5.1 14393  2312
 - SQL Server (Edition|Version): SQl Server 2016 Ent

### Steps to Reproduce
I set  config Set-DbcConfig -Name command.invokedbccheck.excludedatabases -value 'msdb'   and I run Invoke-DbcCheck -AllChecks  -Show Fails -PassThru | Update-DbcPowerBiDataSource -Environment Production  - but I am still getting an error that msdb has duplicate indexes??

### Description of Bug

Should not include the msdb in the duplicateindex test but is
-->

**Comment by SQLDBAWithABeard** [comment]
Thank you - I will exclude msdb from this check anyway but this has also shown that some database checks are not referencing the excluded db global config
