### ISSUE TITLE
FileGrowthCheck Error

### ISSUE THREAD

**Issue by derekjohnston** [sqlcollaborative/dbachecks#507]
## Bug Report
Running Invoke-DbcCheck -Check DatafileAutoGrowthType - I am getting error expect to be kb but got percent - when I physically look at database properties the filegrowth is set to kb not % - after setting the property is there anything else to do? - is there some sort caching?

### Version Information
 - Operating System (Name|Version): windows Server 2016 Standard
 - PowerShell Version: 5.1 14393  2312
 - SQL Server (Edition|Version): SQl Server 2016 Ent

### Steps to Reproduce
Running Invoke-DbcCheck -Check DatafileAutoGrowthType - I am getting error expect to be kb but got percent - when I physically look at database properties the filegrowth is set to kb not % 

### Description of Bug

Should expect test reflect the changes to filegrowth
-->

**Comment by SQLDBAWithABeard** [comment]
Hmm, can I have some more information about this please?

I cannot reproduce this error. Is it happening for all databases? could you provide some screenshots,, which versions of SQL are you targetting?
