### ISSUE TITLE
Slow Loading Times

### ISSUE THREAD

**Issue by adamfortuno** [sqlcollaborative/dbachecks#508]
I downloaded and installed dbachecks this afternoon, and I noticed it took a bit to import the module. Anyone else seeing that?

Here is what I ran:

```Powershell
measure-command { import-module dbachecks }
```
Here is the load duration...
```
Days              : 0
Hours             : 0
Minutes           : 1
Seconds           : 46
Milliseconds      : 175
Ticks             : 1061756057
TotalDays         : 0.00122888432523148
TotalHours        : 0.0294932238055556
TotalMinutes      : 1.76959342833333
TotalSeconds      : 106.1756057
TotalMilliseconds : 106175.6057
```
Specifics about the machine...
* Host Type: Virtual
* Processor: 4 x 2 ghz
* RAM: 12 GB
* Windows 10: 10.0.14393 Build 14393
* Powershell: 5.1.14393.2214

And, here is how I installed the module:

1. Save module and dependent modules.
```Powershell
Save-Module -Name dbachecks -Path $env:temp
```
2. Copied the module files to the host.
1. Copied the module files to "C:\Program Files\WindowsPowerShell\Modules".
1. Launched a Powershell session.

**NOTE:** The test machine I'm using doesn't have access to the internet.

**Comment by potatoqualitee** [comment]
hey adam - it's likely your execution policy. please check out https://dbatools.io/import-times/, specifically the link to http://www.powertheshell.com/understanding-execution-policy/

I also use dbatools offline and import at 4 seconds with a similar setup

**Comment by adamfortuno** [comment]
Thank you @potatoqualitee! I had no idea that the execution policy checks took so long, but it makes a lot of sense.

I spawned a Windows 2016 box, and I installed the module (and dependent modules) using the process from my first post (don't judge me). When I loaded `dbachecks`, I get the following....

![image](https://user-images.githubusercontent.com/30395811/42650597-ce79d786-85da-11e8-94d5-6e840f3661d3.png)

If I set my execution policy to `bypass`, I get the following...

![image](https://user-images.githubusercontent.com/30395811/42650587-c7814b6c-85da-11e8-8b65-48508042845d.png)

I shave about a second and a half. Does that number sound about right to you?

When the module loads, I get held up at the points labeled `HERE`.
```
[HERE]VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.139\dbachecks.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program
Files\WindowsPowerShell\Modules\dbachecks\1.1.139\xml\dbachecks.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module dbachecks.
[HERE]VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.139\dbachecks.psm1'.
VERBOSE: Exporting function 'Import-ModuleFile'.
VERBOSE: Exporting function 'Get-CheckFile'.
VERBOSE: Exporting function 'Get-CheckRepo'.
...
VERBOSE: Importing function 'Update-DbcRequiredModules'.
```

At the end of the day, I can live with 7-seconds to load. I'm just not the sharpest tool in the shed so never hurts to make sure I'm not mucking something up.

**Comment by potatoqualitee** [comment]
hey @adamfortuno - those speeds are way nicer! 23% better loading time is minimal, but overall yeah 7.7 seconds for 4 modules sounds reasonable to me

**Comment by SQLDBAWithABeard** [comment]
Closing this as it seems ok - Feel free to open if you think we need to look into it more
