### ISSUE TITLE
-Database should only check databases listed and exclude all others

### ISSUE THREAD

**Issue by markallisongit** [sqlcollaborative/dbachecks#509]
## Feature Request
   
When I include the `-Database` parameter, I want dbachecks to only check those databases. For instances that have hundreds of database on, it is a pain to have to list hundreds of dbs in the `-ExcludeDatabase` switch.
   
### What should be able to be excluded from being tested ?
    
Exclude all user databases not listed in the `-Database` parameter.

**Comment by SQLDBAWithABeard** [comment]
This will take a decent amount of re-coding but can certainly be done

**Comment by SQLDBAWithABeard** [comment]
There is none at present ☹️. I think it was intended initially for that purpose but has not been coded in that way

**Comment by SQLDBAWithABeard** [comment]
PR #533 closes this - going into master today
