### ISSUE TITLE
Get-DbcCheck fails on macOS High Sierra version 10.13.6

### ISSUE THREAD

**Issue by ssubramanian84** [sqlcollaborative/dbachecks#510]
### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? - version 1.1.139 

### Version Information
 - Operating System (Name|Version): macOS High Sierra Version 10.13.6
 - PowerShell Version: Core 6.0.2
 - SQL Server (Edition|Version): NA

### Steps to Reproduce
1. Executed Find-Module dbachecks - this returns version # 1.1.139
2. Executed Get-Module dbachecks - this returns nothing.
3. Executed Get-DbcCheck - this returns saying that I need to execute Import-Module dbachecks
4. Executed Import-Module dbachecks - this returns the following powershell console output.

PS /Users/shivrams> Import-Module dbachecks                                                                                     
WARNING: [07:39:06][Register-PSFParameterClassMapping] Failed to update property mapping for Computer : Microsoft.DnsClient.Commands.DnsRecord_A. This is likely happening on some Linux distributions due to an underlying .NET issue and means the parameter class cannot be used. | The following exception occurred while retrieving member "SetTypePropertyMapping": "Could not load file or assembly 'System.Data.SqlClient, Version=4.2.0.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
"
Import-Module : Exception calling "InvokeScript" with "4" argument(s): "Exception calling "InvokeScript" with "4" argument(s): "You cannot call a method on a null-valued expression.""
At line:1 char:1
+ Import-Module dbachecks
+ ~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], MethodInvocationException
+ FullyQualifiedErrorId : CmdletInvocationException,Microsoft.PowerShell.Commands.ImportModuleCommand

### Description of Bug
I am seeing this error when simply trying to install/import the module.

**Comment by potatoqualitee** [comment]
Hello, we currently do not support PowerShell Core, unfortunately. We hope to support Core once SMO has been fully ported to Core.

Chrissy
