### ISSUE TITLE
Check that all tempdb files are the same size

### ISSUE THREAD

**Issue by garethnewman** [sqlcollaborative/dbachecks#512]
## Feature Request
   
I want a new tempdb check. This check should be to ensure that all tempdb files are the same size. Recently found a bug with our SQL install scripts where sometimes it could fail and create 3 files at 20gb and 1 file at 8mb as an example. 🤦‍♀️

**Comment by SQLDBAWithABeard** [comment]
Thank you @garethnewman  I shall add this check - 

Could please you also raise an issue on dbatools at https://github.com/sqlcollaborative/dbatools/issues for Test-DbaTempDbConfiguration and when it is added to there I will revert back to the dbatools version

**Comment by garethnewman** [comment]
Thanks for sorting this Rob, I did write this for DbaTools but I couldn't figure out how to make DbaChecks look at my version to test it. :(
