### ISSUE TITLE
Set-DbcConfig -append doesn't work correctly.

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbachecks#535]
### General Troubleshooting steps
- checked on current dev branch
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Sever 2016
 - PowerShell Version: v5
 - SQL Server (Edition|Version): 

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/981370/44582586-15e05800-a770-11e8-89dd-ad2c8eb0dd03.png)

### Description of Bug
When you use `-Append` it seems to invalidate the array and then using that in checks the databases don't get excluded.
The first use of `-Append` it loses the commas between the existing database names, on the second use it changes the original dbs into an object.
Could be causing issue #496

**Comment by SQLDBAWithABeard** [comment]
@FriedrichWeinmann  is this a PSframework thing or a DbaChecks coding thing?

**Comment by FriedrichWeinmann** [comment]
It's in how Set-DbcConfig appends items to an array:
https://github.com/sqlcollaborative/dbachecks/blob/6a1f60cf52280a535f6309532b51d49e9b21d210/functions/Set-DbcConfig.ps1#L65
If in this line the previous value is already an array, it will _not_ be added to that array, but instead a new array will be created with the original array in the first index position and the added value in the second position.
You'd want to check whether the previous value is already a collection and if so add the new value to the existing collection.

**Comment by SQLDBAWithABeard** [comment]
Fixed with commit 610330d10b332da857f6392e89a06bd882f9851e

![image](https://user-images.githubusercontent.com/6729780/44715995-1569f900-aab1-11e8-9eba-bff6ac1050c8.png)
