### ISSUE TITLE
Email submission

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbachecks#536]
````
Couple of DBAChecks improvement ideas:

1. If it encounters a job that has not completed successfully (i.e. it failed, or was cancelled), then a further check is made to see if the job is now running, and thus not highlighting it as being an error.

An example of such a job might be a Replication agent job which was cancelled, then retried successfully, and is now running.

2. Have a configuration to allow offline databases to be excluded from certain checks.

I love DBAChecks, BTW!
````

**Comment by SQLDBAWithABeard** [comment]
I'm conflicted about number 1 - need to mull it over. It is not a monitoring tool but it is used as a post-refresh, post-maintenance status check where that could be useful

**Comment by SQLDBAWithABeard** [comment]
Number 2 I agree

**Comment by wsmelton** [comment]
Well I guess it is a legitimate check to see a failure count on a job that runs frequently.

So to check in the description given you could just have a config for consecutive failures before a job gets flagged. Then even if the jobs last run was failure and the current state is running is irrelevant.

**Comment by SQLDBAWithABeard** [comment]
Number 2 is completed with @jpomfret recent improvements

**Comment by SQLDBAWithABeard** [comment]
I think these are good now - shout if I am wrong
