### ISSUE TITLE
Version 1.1.150 - The term 'Send-DbcMailMessage' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by sam-bryant** [sqlcollaborative/dbachecks#539]
### General Troubleshooting steps
I've uninstalled all versions of dbachecks and ran the following commands:
```
Install-Module dbachecks -RequiredVersion 1.1.150 
Import-Module dbachecks -RequiredVersion 1.1.150 -Verbose -Force
Invoke-DbcCheck -ComputerName 'ServerName' -Check Server -PassThru | Send-DbcMailMessage -To '...' -From '...' -SmtpServer '...'
```

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`
Yes, 1.1.150

![image](https://user-images.githubusercontent.com/6729780/37113488-60e5e172-21fa-11e8-8115-814edfbfabb6.png)

- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 10
 - PowerShell Version: 5
 - SQL Server (Edition|Version): N/A

### Steps to Reproduce
Uninstall previous versions of dbachecks then run the following commands:
```
Install-Module dbachecks -RequiredVersion 1.1.150 
Import-Module dbachecks -RequiredVersion 1.1.150 -Verbose -Force
Invoke-DbcCheck -ComputerName 'ServerName' -Check Server -PassThru | Send-DbcMailMessage -To '...' -From '...' -SmtpServer '...'
```

### Description of Bug
PS C:\Users\sbryant> Import-Module dbachecks -RequiredVersion 1.1.150 -Verbose -Force
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.150\dbachecks.psd1'.
VERBOSE: Loading 'FormatsToProcess' from path 'C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.150\xml\dbachecks.Format.ps1xml'.
VERBOSE: Populating RepositorySourceLocation property for module dbachecks.
VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.150\dbachecks.psm1'.
VERBOSE: Exporting function 'Import-ModuleFile'.
VERBOSE: Exporting function 'Get-CheckFile'.
VERBOSE: Exporting function 'Get-CheckInformation'.
VERBOSE: Exporting function 'Get-CheckRepo'.
VERBOSE: Exporting function 'Get-ComputerName'.
VERBOSE: Exporting function 'Get-DatabaseDetail'.
VERBOSE: Exporting function 'Get-Instance'.
VERBOSE: Exporting function 'Get-Version'.
VERBOSE: Exporting function 'Invoke-ConfigurationScript'.
VERBOSE: Exporting function 'New-Json'.
VERBOSE: Exporting function 'Select-DefaultView'.
VERBOSE: Exporting function 'Set-DatabaseForIntegrationTesting'.
VERBOSE: Exporting function 'Clear-DbcPowerBiDataSource'.
VERBOSE: Exporting function 'Export-DbcConfig'.
VERBOSE: Exporting function 'Get-DbcCheck'.
VERBOSE: Exporting function 'Get-DbcConfig'.
VERBOSE: Exporting function 'Get-DbcConfigValue'.
VERBOSE: Exporting function 'Get-DbcReleaseNote'.
VERBOSE: Exporting function 'Get-DbcTagCollection'.
VERBOSE: Exporting function 'Import-DbcConfig'.
VERBOSE: Exporting function 'Invoke-DbcCheck'.
VERBOSE: Exporting function 'Invoke-DbcConfigFile'.
VERBOSE: Exporting function 'Reset-DbcConfig'.
VERBOSE: Exporting function 'Save-DbcRequiredModules'.
VERBOSE: Exporting function 'Send-DbcMailMessage'.
VERBOSE: Exporting function 'Set-DbcConfig'.
VERBOSE: Exporting function 'Start-DbcPowerBi'.
VERBOSE: Exporting function 'Update-DbcPowerBiDataSource'.
VERBOSE: Exporting function 'Update-DbcRequiredModules'.
VERBOSE: Importing function 'Clear-DbcPowerBiDataSource'.
VERBOSE: Importing function 'Export-DbcConfig'.
VERBOSE: Importing function 'Get-DbcCheck'.
VERBOSE: Importing function 'Get-DbcConfig'.
VERBOSE: Importing function 'Get-DbcConfigValue'.
VERBOSE: Importing function 'Get-DbcReleaseNote'.
VERBOSE: Importing function 'Get-DbcTagCollection'.
VERBOSE: Importing function 'Import-DbcConfig'.
VERBOSE: Importing function 'Invoke-DbcCheck'.
VERBOSE: Importing function 'Invoke-DbcConfigFile'.
VERBOSE: Importing function 'Reset-DbcConfig'.
VERBOSE: Importing function 'Save-DbcRequiredModules'.
VERBOSE: Importing function 'Set-DbcConfig'.
VERBOSE: Importing function 'Start-DbcPowerBi'.
VERBOSE: Importing function 'Update-DbcPowerBiDataSource'.
VERBOSE: Importing function 'Update-DbcRequiredModules'.
end-DbcMailMessage : The term 'Send-DbcMailMessage' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At \\modern-woodmen\fdrive\Users\sbryant\My Documents\Workspace\Powershell\dbachecks tests.ps1:3 char:70
 ... me 'ServerName' -Check Server -PassThru | Send-DbcMailMessage -To '.. ...
                                               ~~~~~~~~~~~~~~~~~~~
     CategoryInfo          : ObjectNotFound: (Send-DbcMailMessage:String) [], CommandNotFoundException
     FullyQualifiedErrorId : CommandNotFoundException

I noticed the Send-DbcMailMessage cmdlet is commented out in the FunctionsToExport portion of the .psd1.  I'm guessing this is the cause.

**Comment by SQLDBAWithABeard** [comment]
Hi, Unfortunately we have had some issues with Send-DbcMailMessage so have removed it until they can be resolved.

You can still send an email using the code below

`
$ouputDirectory = (Get-DbcConfigValue -Name app.maildirectory) 
$filename = $outputDirectory + '\file.xml'
Invoke-Dbccheck -OutputFile $fileName -OutputFormat NunitXML

$outputpath = $ouputDirectory  + "\index.html"
$reportunit = "ModulePAth\bin\ReportUnit.exe"
& $reportunit $ouputDirectory

$htmlbody = Get-Content -Path $outputpath -ErrorAction SilentlyContinue | Out-String

Send-MailMessage -To -From -SMTP -body $htmlbody



`
