### ISSUE TITLE
dbachecks.pbix is corrupt or an invalid report file

### ISSUE THREAD

**Issue by francescovista** [sqlcollaborative/dbachecks#544]
### General Troubleshooting steps
run:
`Invoke-DbcCheck -SqlInstance sql2017 -Checks SuspectPage, LastBackup -Show Summary -PassThru | Update-DbcPowerBiDataSource`
run:
`Start-DbcPowerBi
`

![filesarethere](https://user-images.githubusercontent.com/30395256/45126823-7f795100-b1c9-11e8-975e-43bb3972e5dd.PNG)

### Version Information
Operating System (Name|Version): Windows 10 Enterprise
PowerShell Version:
```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  1155
```
SQL Server (Edition|Version):
Microsoft SQL Server Management Studio	13.0.16106.4
Microsoft Analysis Services Client Tools	13.0.1700.441
Microsoft Data Access Components (MDAC)	10.0.15063.0
Microsoft MSXML	3.0 4.0 6.0
Microsoft Internet Explorer	9.11.15063.0
Microsoft .NET Framework	4.0.30319.42000
Operating System	6.3.15063

### Steps to Reproduce
run:
`Invoke-DbcCheck -SqlInstance sql2017 -Checks SuspectPage, LastBackup -Show Summary -PassThru | Update-DbcPowerBiDataSource`
run:
`Start-DbcPowerBi
`

### Description of Bug

before running the first command with `-SqlInstance localhost` I run the command that I copied form your page:

`Invoke-DbcCheck -SqlInstance sql2017 -Checks SuspectPage, LastBackup -Show Summary -PassThru | Update-DbcPowerBiDataSource`

![before](https://user-images.githubusercontent.com/30395256/45126925-e7c83280-b1c9-11e8-85aa-e04ab05b8384.PNG)

I think the data were loaded and maybe they are corrupted. You should put a check that watch out id that instance exists or if the data are alright

**Comment by SQLDBAWithABeard** [comment]
HI @francescovista Please try copying the pbix from 

C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.151\bin

to 

AppData\Local\dbachecks

The version I have from the gallery is working correctly

**Comment by francescovista** [comment]
I copied the pbix from "C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.151\bin" to "AppData\Local\dbachecks" but when I double click on it:

![downloaded](https://user-images.githubusercontent.com/30395256/45183651-d427d500-b278-11e8-9c5c-9ea39c4d8c42.PNG)

So I downloaded a fresh new repository from GitHub and I copied the pbix from there, as you can see the date has changed from 05/09/2018 to 06/09/2018, so is your latest from yesterday but still no joy:

![datechanged](https://user-images.githubusercontent.com/30395256/45183758-194c0700-b279-11e8-8bac-b422a32fbcf9.PNG)

So I fired up Power BI, version Version: 2.61.5192.601 64-bit (August 2018) and I opened the fresh new version downloaded 10 minutes ago:

![errors](https://user-images.githubusercontent.com/30395256/45183840-56b09480-b279-11e8-93ed-62390e25642a.PNG)

the logs are in attach 

[DetailsError.txt](https://github.com/sqlcollaborative/dbachecks/files/2358692/DetailsError.txt)

**Comment by SQLDBAWithABeard** [comment]
Excellent, does that mean it is now working for you?

**Comment by LowlyDBA** [comment]
I've been experiencing this issue with a lot of my users.. when I upgraded *my* PowerBI version (thanks to the not so subtle prompts every time I open it) and save the report, it breaks backwards compatibility. It was also the August update, not sure if this happens with every monthly update or not..
