### ISSUE TITLE
New commands for historical information as seen in demo

### ISSUE THREAD

**Issue by potatoqualitee** [sqlcollaborative/dbachecks#550]
I saw the updated demo at SQLGLA and loved it. I realized that the historical thing should perhaps be a couple commands plus an update to the PowerBI with the dbachecks styling /cc @ClaudioESSilva 

Install-DbcHistoricalDb
Update-DbcHistory?

Rob can you link your demo including PBI?

**Comment by SQLDBAWithABeard** [comment]
Implemented with reports to database and new PowerBi
