### ISSUE TITLE
DiskAllocationUnit - 64K for SQL and 4K for OS

### ISSUE THREAD

**Issue by MikeyBronowski** [sqlcollaborative/dbachecks#561]
### Question

Hi, 

currently DiskAllocationUnit checks for 64K allocUnit on all drives available to SQL Server.

Do you think would it be useful to create configuration to exclude specific drives from the checks (OS, Temporary Backup, etc), where 64K allocUnit is not required?

**Comment by adamfortuno** [comment]
I think that's a good idea. Default too all drives, but let people pass 
a list of drive letters they want to ignore.

------ Original Message ------
