### ISSUE TITLE
Import-PowerShellDataFile dependency

### ISSUE THREAD

**Issue by andoius** [sqlcollaborative/dbachecks#568]
With:

- dbatools : 0.9.495
- pester 4.4.2
- psframework 0.10.29.160

- dbachecks 1.1.160

powershell

> Major  Minor  Build  Revision
> 4      0      -1     -1    

installation fails die to a dependancy on "Import-PowerShellDataFile" .. [this module](https://docs.microsoft.com/en-gb/powershell/module/Microsoft.PowerShell.Utility/Import-PowerShellDataFile?view=powershell-6&viewFallbackFrom=powershell-4.0) is only available in powershell 5+ therefore the following is incorrect

> Client requirements
> PowerShell 4+ is required.
> Automatic installation of the dependent modules will only be provided via the PowerShell Gallery.

**Comment by SQLDBAWithABeard** [comment]
Paging @FriedrichWeinmann as this is a psframework command

**Comment by pauby** [comment]
@SQLDBAWithABeard Import-PowerShellDataFile is a PowerShell cmdlet and is only available in PS 5+ (as @andoius says). I am about to produce the `dbachecks` Chocolatey module and I'll mark it as PS 5+ for the time being.

**Comment by FriedrichWeinmann** [comment]
Argh, totally lost track of that one :(
Added an issue on my repo, currently working on integrating the bulk of issues there and this should be in it:
https://github.com/PowershellFrameworkCollective/psframework/issues/368
