### ISSUE TITLE
Database.Test - Unused Indexes

### ISSUE THREAD

**Issue by valstrubhar** [sqlcollaborative/dbachecks#586]
Per the dbatools.io site the name of the command should be 'Find-DbaDBUnusedIndex' and not 'Find-DbaUnusedIndex'

Describe "Unused Index" -Tags UnusedIndex, $filename {
        if ($NotContactable -contains $psitem) {
            Context "Testing Unused indexes on $psitem" {
                It "Can't Connect to $Psitem" {
                    $false  |  Should -BeTrue -Because "The instance should be available to be connected to!"
                }
            }
        }
        else {
            Context "Testing Unused indexes on $psitem" {
                try {
                    @($results = Find-DbaUnusedIndex -SqlInstance $psitem -Database $Database -ExcludeDatabase $ExcludedDatabases -EnableException).ForEach{
                        It "$psitem on $($psitem.SQLInstance) should return 0 Unused indexes" {
                            @($results).Count | Should -Be 0 -Because "You should have indexes that are used"
                        }
                    }
                }
                catch {
                    It -Skip "$psitem on $($psitem.SQLInstance) should return 0 Unused indexes" {
                        @($results).Count | Should -Be 0 -Because "You should have indexes that are used"
                    }
                }
            }
        }
    }

**Comment by SQLDBAWithABeard** [comment]
This was resolved a while ago (I cant find where!)
