### ISSUE TITLE
InstanceConnection Test Returns Error for AuthScheme Against Local Instances

### ISSUE THREAD

**Issue by kylejdoyle** [sqlcollaborative/dbachecks#601]
### Steps to Reproduce

Run the InstanceConnect Test against a local instance of SQL Server.

### Description of Bug

The auth scheme step will always fails if the instances being checked includes a local instance.  Perhaps it would be better to first check if the instance being checked is local to the server and if it is always accept a result of NTLM.

**Comment by SQLDBAWithABeard** [comment]
You can use skip.connection.auth to skip the authentication check but are you asking for the check to specifically test for local instance first?

**Comment by kylejdoyle** [comment]
Yes, there are a couple ways to handle this as it is now.  However, since this is something that is always true, connecting to local instance is always NTLM, I was thinking perhaps it should be built into the check versus working around it every time.

**Comment by SQLDBAWithABeard** [comment]
I have coded a fix for the next release

**Comment by kylejdoyle** [comment]
This should work, but I was just testing and it looks like there is a bug in Test-DbaConnection which shows the NetBIOSName incorrectly as the FQDN.  I changed the IF condition to $Connection.ComputerName -eq $ENV:COMPUTERNAME and it works beautifully.

**Comment by SQLDBAWithABeard** [comment]
ah grrr, didnt get that in my lab, I ummed and ahed as to which one to use - I'll change it. Thanks for testing :-)
