### ISSUE TITLE
Auto Refresh PowerBI

### ISSUE THREAD

**Issue by Jya2019** [sqlcollaborative/dbachecks#602]
## Feature Request
   
"You will need to refresh the Power BI dashboard every time to see the new results" - Is there any way that this can be automated?  
   
 
## Additional information    
    
I need to activate the refresh button to see the new information from the .json file but currently it is done manually.  I was thinking of even closing PowerBI and starting it up again but I still have to manually refresh

Thanks

**Comment by SQLDBAWithABeard** [comment]
Unfortunately not - Power Bi Desktop is a designer - you would have to publish the report to a PowerBi Server or to the cloud to get auto or scheduled refreshes
