### ISSUE TITLE
Wiki update for Sending-Mail section

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbachecks#603]
## Wiki Update
The example here needs to be removed or changed since `Send-DbcMailMessage` has been excluded from the module.
https://github.com/sqlcollaborative/dbachecks/tree/9330fe53b50c385e0d8ce8e463279fd778eeb82b#sending-mail

A suggestion on how to send emails still from @SQLDBAWithABeard:
https://github.com/sqlcollaborative/dbachecks/issues/539#issuecomment-418649934
```
$ouputDirectory = (Get-DbcConfigValue -Name app.maildirectory)
$filename = $outputDirectory + '\file.xml'
Invoke-Dbccheck -OutputFile $fileName -OutputFormat NunitXML

$outputpath = $ouputDirectory + "\index.html"
$reportunit = "ModulePAth\bin\ReportUnit.exe"
& $reportunit $ouputDirectory

$htmlbody = Get-Content -Path $outputpath -ErrorAction SilentlyContinue | Out-String

Send-MailMessage -To -From -SMTP -body $htmlbody
```

**Comment by shaneis** [comment]
o/ @SQLDBAWithABeard 

We can close this off, right?
#605 seems to handle this
