### ISSUE TITLE
DBACHECKS failing after dbatools.dll gets a updated timestamp

### ISSUE THREAD

**Issue by gun10** [sqlcollaborative/dbachecks#606]
#### Title: DBACHECKS failing after dbatools.dll gets a updated timestamp

**Architecture SQL:** SQL Server AlwaysOn Availability Group (two node WSFC)
**DBACHECKS implementation:** per windows server => through monitoring agent windows service => custom monitoring script => cmd command line => powershell.exe -File  "C.\....\RunCriticalHADR.ps1"  (or powershell -command .. ) => Server1 checks Server1, Server2 => and vice versa Server2 checks Server2, Server1
**the runscript:** contains set-DbcConfig  and Invoke-DbcCheck -Checks WarningHADR 
**WarningHADR** is triage of the HADR.Tests.ps1 one in the ..\Modules\dbachecks\checks folder

```powershell

# this is the RunCriticalHADR.ps1
# the module[s] get loaded from C:\Windows\System32\WindowsPowerShell\v1.0\Modules\dbachecks
# pester module gets loaded from C:\Program Files\WindowsPowerShell\Modules\Pester\4.4.1

          #region execution dbachecks
 $Null = { 
Import-Module dbachecks
set-DbcConfig -Name app.checkrepos -Value "C:\..\xyz-sql-monitoring" -Append
set-DbcConfig -Name domain.name -Value (Get-WmiObject win32_computersystem).Domain
Set-DbcConfig -Name app.cluster -Value (Get-DbaWsfcCluster | Select-Object -ExpandProperty Name)
Set-DbcConfig -Name app.sqlinstance -Value 'MSSQLSERVER'
Set-DbcConfig -Name app.computername -Value @(Get-DbaWsfcNode | Select-Object -ExpandProperty Name)
                    
}
$res = Invoke-DbcCheck -Checks WarningHADR -PassThru -Show None -WarningAction SilentlyContinue 

... further handling $_.TotalCount and $res.FailedCount and $exitcode


        #endregion execution dbachecks

```

## Steps to Reproduce

- Download dbachecks and dependent modules from github master branch
- Offline install on Servers via puppet and chocolatey 
- Get-ChildItem -Path C:....... -Recurse  | Unblock-File
- manual check in ISE and PS Console
- manual check in cmd window 
- Automation: Implement custom monitoring scripts "RunCriticalHADR" and "RunWarningHADR" in monitoring tool 
- let it run every 2 minutes
- visual check and send alert if the failed checks get reported
- Monitor the run-script exit code until it breaks. 
- Verify in PS Console import-module dbatools failing
- ~Back to start: Offline install on Servers via manually or choco install

## Expected Behavior

I save the module and all folders and files have the same timestamp. 
my dbachecks work fine!
![image](https://user-images.githubusercontent.com/21216654/53484376-00801980-3a84-11e9-83f4-fe85ccb4d908.png)

![image](https://user-images.githubusercontent.com/21216654/53489254-04feff00-3a91-11e9-9938-7d263216ebf4.png)

## Actual Behavior
After many successful checks over hours or even days my dbachecks stop working.

- I found that the import-module dbatools is stopping dbachecks of doing its job
- and that dbatools.dll gets a updated timestamp and its file size is now 0 Kb (zero Kilobyte)
![image](https://user-images.githubusercontent.com/21216654/53484987-5f925e00-3a85-11e9-8f12-bb2e8fb83da8.png)

![image](https://user-images.githubusercontent.com/21216654/54120110-32d03600-43f7-11e9-87ff-432420631465.png)

#### what I checked up to now
-  delete/copy the original module files => dbachecks work fine
-  checked if puppet or chocolatey are over writing the .dll => answer NO
-  checked the virus scanner if it logs any actions on DBATOOLS
-  simulate the checks under my windows account and the monitoring-agent service-account and NT AUTHORITY SYSTEM 
-  checked all Logs: Windows Event, SQL Errorlog, SQL trace logs (Login failed), my run-script log

#### Additional Questions / Areas of investigation
-  I read some posts (not many) about dbatools.dll is there a difference between github and ps gallery version regarding dbatools.dll ? 
- could it be a concurrence issue? see: Server1 checks Server1, Server2 and vice versa => I expect it to be two "atomic" powershell sessions, even if they may run at the same time !!
- where else should I put an eye on?
- might it be a timing issue - to many of the same/similar checks - 2 minutes and 5 minute interval

## Environmental data

 - PowerShell:  
![image](https://user-images.githubusercontent.com/21216654/53483848-be0a0d00-3a82-11e9-9ff0-b3e15f973fab.png)

 - - SQL Server:  Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64)   Mar 18 2018 09:11:49   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Standard 10.0 <X64> (Build 14393: ) (Hypervisor)

**Comment by potatoqualitee** [comment]
Does this happen on the most recent version of dbatools? Fred updated it last week and this _should_ be addressed.

**Comment by gun10** [comment]
>  
> Does this happen on the most recent version of dbatools? Fred updated it last week and this _should_ be addressed.

Hi, "most recent"  "last week" NO. 
Beginning of January I guess - 0.9.721 dbatools version. I'll try PS Gallery this time and give you feedback here, 
thanxs for fast reply

**Comment by potatoqualitee** [comment]
Please let us know - update to the latest version, I added some additional changes last week.

**Comment by gun10** [comment]
> 
> 
> Please let us know - update to the latest version, I added some additional changes last week.

**Comment by gun10** [comment]
> 
> 
> Please let us know - update to the latest version, I added some additional changes last week.

Hi Chrissy,
I used DBATOOLS Module Version "0.9.773"  last week fron PS Gallery.
I was on it now, after one week of holidays and would call it a good test period.
Big thanks for the toolbox to all contributors!
regards Markus

**Comment by potatoqualitee** [comment]
excellent news! thanks for the update!
