### ISSUE TITLE
Several Checks Failing on Non-Readable Secondaries

### ISSUE THREAD

**Issue by kylejdoyle** [sqlcollaborative/dbachecks#611]
The LogfileCount, FileGroupBalanced, and DatafileAutoGrowthType checks are failing on non-readable secondaries.  Something like `-and ($Psitem.IsAccessible -eq $true)` needs to be added to all of these checks in the Databases.Tests.ps1 on lines 535, 615, and 730.

**Comment by shaneis** [comment]
So you found the error, troubleshooted it, figured out a fix, and created an issue.

I'd personally love to see a PR as well :)

If not let us know, we can create one or throw it up to "good-first-issue" label

**Comment by wsmelton** [comment]
Check #432 as this is already done for some checks...

**Comment by kylejdoyle** [comment]
Will do, thanks.
