### ISSUE TITLE
Unable to load the new version 1.1.173 after updating from 1.1.171

### ISSUE THREAD

**Issue by LSLasseAlfastsen** [sqlcollaborative/dbachecks#619]
## Issue

After updating the dbachecks module using update-dbcrequiredmodules (the command ran successfully)

i am unable to load the new version in powershell.

I noticed the problem after updating it on my own pc, after the update Invoke-DbcCheck would do absolutely nothing.

After that i tried to do a clean install of dbachecks, ie.

Delete all module folders (including a dbachecks folder in local appdata)

```PowerShell
Install-Module dbatools
Install-Module Pester -SkipPublisherCheck -Force
Install-Module PSFramework
Install-Module dbachecks
```

But after doing this i got the following error output

```PowerShell
Get-ChildItem : Cannot find path 'C:\Program 
Files\WindowsPowerShell\Modules\dbachecks\1.1.171\checks' because it does
not exist.
At line:8 char:24
+         $repofiles += (Get-ChildItem "$repo\*.Tests.ps1")
+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...\1.1.171\checks:String) [Get- 
ChildItem], ItemNotFound
   Exception
    + FullyQualifiedErrorId : 
PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand
```

So it has left some weird references to the old version directory, if i install 1.1.171 again checks will run.

I then tried on a different machine and after updating to 1.1.173 i get the following error
    WARNING: Failed to import C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.173\internal\configurations\configuration.ps1

This is unexpected behaviour

### Version Information
 - Operating System Windows 10 Pro (1903 and 1809) 
 - PowerShell Version:  5.1.18362.113

**Comment by SQLDBAWithABeard** [comment]
Annoyingly, this sometimes happens and I cannot trace why.

It is usually fixed with a Reset-DBcConfig
