### ISSUE TITLE
dbachecks compatibility with PowerShell Core (on Linux)

### ISSUE THREAD

**Issue by gbuczylowski** [sqlcollaborative/dbachecks#620]
Any plans to make dbachecks compatible with PowerShell Core?

I'm running dbatools in docker Linux container with PowerShell Core, and it would be great to be able to run dbachecks as well.

**Comment by SQLDBAWithABeard** [comment]
Yes, that is definitely something on the roadmap.

Now if only someone can invent 48 hours in a day or clone me (or give me the energy of Chrissy! :-) )

**Comment by SQLDBAWithABeard** [comment]
It imports
![image](https://user-images.githubusercontent.com/6729780/58734084-53080380-83ee-11e9-8502-015e0391660d.png)

Invoke-DbcCheck runs
Instance, Agent and Database checks run
Update-DbcPowerBi runs
![image](https://user-images.githubusercontent.com/6729780/58733927-e7be3180-83ed-11e9-9890-43b1635109d4.png)

Export and Import Config runs
![image](https://user-images.githubusercontent.com/6729780/58733983-0cb2a480-83ee-11e9-8049-6a6a47178ee2.png)


Copy the json to the correct path on windows and it opens in powerbi
![image](https://user-images.githubusercontent.com/6729780/58734015-2358fb80-83ee-11e9-8202-f0774a969002.png)

![image](https://user-images.githubusercontent.com/6729780/58733319-23f09280-83ec-11e9-85d0-4ad6f80295b3.png)

**Comment by SQLDBAWithABeard** [comment]
Still some things to do

Will it run against on Linux against a windows machine?

The other checks files will need to be checked

Other commands need to be checked

Hmm - I could do some of that

Get-DbcCheck works
![image](https://user-images.githubusercontent.com/6729780/58734213-b72ac780-83ee-11e9-8f8f-fe3cef93e0c5.png)

Get-DbcConfig works

![image](https://user-images.githubusercontent.com/6729780/58734254-d4f82c80-83ee-11e9-9f39-25c7bdc43216.png)

Get-DbcConfigValue works

**Comment by SQLDBAWithABeard** [comment]
![image](https://user-images.githubusercontent.com/6729780/58734314-0ffa6000-83ef-11e9-991d-01570dddf257.png)

Set-DbcConfig works

![image](https://user-images.githubusercontent.com/6729780/58734385-36200000-83ef-11e9-87f4-7742ca3a19f8.png)

Set-DbcConfig -Append works

![image](https://user-images.githubusercontent.com/6729780/58734513-826b4000-83ef-11e9-9769-555e56b764fa.png)

Reset-DbcConfig gives warnings from PSFramework but does appear to work

![image](https://user-images.githubusercontent.com/6729780/58734590-b8102900-83ef-11e9-942a-29aa1e297e67.png)

![image](https://user-images.githubusercontent.com/6729780/58734630-cfe7ad00-83ef-11e9-9f65-247ed9adcd8b.png)

**Comment by SQLDBAWithABeard** [comment]
and the tests pass :-)

Feel free to clone the development branch (because I am stupid and thought I was on a new branch locally which I had created) and test 

by loading the module from the psd1

Import-Module PATHTOLOCALREPOOFDBACHECKS\dbachecks.psd1

**Comment by gbuczylowski** [comment]
I've run some tests agains SQL in Windows container, and the module loads just fine, but some tests fail to load assertion files due to incorrect case.

Since Linux is case sensitive and all assertion files are in Pascal Case, they need to be loaded from .test.ps1 files with the right case.

e.g.
../dbachecks/checks/Agent.Tests.ps1 loads Agent.assertions.ps1 in line 2, but the accutal file name is Agent.Tests.ps1, which only causes issues in Linux

. $PSScriptRoot/../internal/assertions/Agent.assertions.ps1

**Comment by SQLDBAWithABeard** [comment]
ok going into dev branch now
