### ISSUE TITLE
Active Directory user not found when name different from samAccountName

### ISSUE THREAD

**Issue by alhandra** [sqlcollaborative/dbachecks#622]
### General Troubleshooting steps
Using latest version of dbachecks

- [ ] Verified errors are not related to permissions?
No
- [ ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?
YES 

### Version Information
 - Operating System (Name|Version): 
Windows 2008R2
 - PowerShell Version: 
PS5.1
 - SQL Server (Edition|Version): 
Microsoft SQL Server 2008 R2 (SP2) - 10.50.4297.0 (X64)   Nov 22 2013 17:24:14   Copyright (c) Microsoft Corporation  Standard Edition (64-bit) on Windows NT 6.1 <X64> (Build 7601: Service Pack 1) 

### Steps to Reproduce
<--  
**Test-DbaWindowsLogin -SqlInstance INSTANCE  -FilterBy LoginsOnly -Debug**
DEBUG: 106788 | [16:20:39][Test-DbaWindowsLogin] Connected to:
INSTANCE.
DEBUG: 106807 | [16:20:39][Test-DbaWindowsLogin] Search restricted to logins.
DEBUG: 106828 | [16:20:39][Test-DbaWindowsLogin] Parsing Login COMPANY-PT\bckadmin.
DEBUG: 113190 | [16:20:39][Get-DbaADObject] Searching for bckadmin under domain
 COMPANY-PT in SamAccountName format
WARNING: [16:20:39][Test-DbaWindowsLogin] AD Searcher Error for bckadmin.
DEBUG: [16:20:39][Test-DbaWindowsLogin] AD Searcher Error for bckadmin.

However If we Run
**PS C:\Users\mylogin> Get-AdUser -Identity bckadmin**
DistinguishedName : CN=THE NAME OF USER,OU=Generics,OU=Users,OU
                    =Company,DC=vf-pt,DC=internal,DC=company,DC=com
Enabled           : True
GivenName         :
Name              : THE NAME OF USER
ObjectClass       : user
ObjectGUID        : c33f9290-d40b-4c9b-b9df-039bd6adf8af
SamAccountName    : BCKADMIN
SID               : S-1-5-21-682003330-2049760794-1801674531-135507
Surname           :
UserPrincipalName : BCKADMIN@company.com

-->

### Description
Users on COMPANY-PT (a child domain of COMPANY-ROOT) are not being found by Test-DbaWindowsLogin. Same thing happens with groups.
I expect them to find since using the cmdlet Get-AdUser they correctly appear.

Notes: 
 COMPANY-PT is a CHILD domain of COMPANY-ROOT.
 All users on COMPANY-ROOT are being correctly found

**Comment by SQLDBAWithABeard** [comment]
Hi @alhandra 

Thank you so much for raising this. This is a dbatools issue and not a dbachecks issue. Please could you raise an issue in the dbatools repository at this link

https://github.com/sqlcollaborative/dbatools/issues/new?assignees=&labels=%5Bbugs+life%5D&template=Bug_Report.md&title=%5BBug%5D
