### ISSUE TITLE
Dbachecks using unkown commands after DbaTools 1.0.5 update

### ISSUE THREAD

**Issue by JayPalker** [sqlcollaborative/dbachecks#624]
### General Troubleshooting steps
- [X] Verified running the latest release of dbachecks? 

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`

![image](https://user-images.githubusercontent.com/6729780/37113488-60e5e172-21fa-11e8-8115-814edfbfabb6.png)

- [X] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows 7
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): SQL Server 2014/2016

### Steps to Reproduce

Update dbatools to 1.0.5 and run OrphanedUser check.

 - [ ] Attach any screenshots (if possible/allowed)
 - [ ] Attach output from PowerShell console (if possible/allowed)

### Description of Bug

It would appear that some DbaTools commands have changed with the latest DbaTools release 1.0.5, which has broken some of the DbaChecks tests. In this specific instance, Get-DbaOrphanUser no longer exists and has been replaced by Get-DbaDbOrphanUser. Rolling back to DbaTools 0.9.834 is a workaround.

**Version 0.9.834 Command Get-DbaOrphanUser (Current Command: Get-DbaDbOrphanUser)**
CommandNotFoundException: The term 'Get-DbaOrphanUser' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.173\checks\Database.Tests.ps1: line 783

I believe the following exhibit the same issue:

**Version 0.9.834 Command Test-DbaSQLBuild (Current Command: Test-DbaBuild)**
Context Checking that build is still supportedby Microsoft for localhost
CommandNotFoundException: The term 'Test-DbaSQLBuild' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
        at Assert-InstanceSupportedBuild, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.173\internal\assertions\Instance.assertions.ps1: line 110
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.173\checks\Instance.Tests.ps1: line 324

**Version 0.9.834 Command Test-DbaServerName (Current Command: Test-DbaInstanceName)**
Context Testing instance name matches Windows name for localhost
CommandNotFoundException: The term 'Test-DbaServerName' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.173\checks\Instance.Tests.ps1: line 278

**Version 0.9.834 Command Test-DbaTempdbConfig no longer has a SqlServer parameter** 
**https://docs.dbatools.io/#Test-DbaTempDbConfig**

Context Testing TempDB Configuration on localhost
ParameterBindingException: A parameter cannot be found that matches parameter name 'SqlServer'. This failure might be caused by applying the default parameter binding. You can disable the default parameter binding in $PSDefaultParameterValues by sett
ing $PSDefaultParameterValues["Disabled"] to be $true, and retry. The following default parameter was successfully bound for this cmdlet when the error occurred: -EnableException
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.1.173\checks\Instance.Tests.ps1: line 111

**Comment by Geo-Ron** [comment]
Tripped over the same thing here...

Reverting dbatools to version 0.9.834 fixes dbachecks.

**Comment by shaneis** [comment]
Coolio - thanks for the info. Would either of you fine people like to create a PR to fix this? 

dbatools has a lovely command called `Invoke-DbatoolsRenameHelper` that can make this nice and simple
