### ISSUE TITLE
Improper use of switch() leads to long running time

### ISSUE THREAD

**Issue by ashdar** [sqlcollaborative/dbachecks#635]
## Bug Report
After updating from 1.1.173 to 1.2.5, I found that the time required for my daily tests when from 0.75 hours to about 2.5 hours. 

### General Troubleshooting steps
- [X] Verified running the latest release of dbachecks? 
- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows|7
 - PowerShell Version: 5.1
-->

### Steps to Reproduce
<--  
  PLEASE include as much information as possible if this is a bug report.
  The more you include the faster we can identify the problem and get it fixed
-->
Reproducing this seems difficult because you need servers with large error logs before you notice. A large list of active tags/checks compounds the problem to the point where it is overwhelming. I'm testing against prod servers that haven't had their logs rotated for months-to-years.

### Description of Bug
I'll be submitting a patch later today (I expect), but:

If you look at Instance.Assertions.ps1, in the Get-AllInstanceInfo function, there is a switch statement at line 16:
switch ($tags)

$tags is an array. This usage has the effect of "looping" switch on each element in the $tags array. (TIL. this is something that I did not know that switch did.)

A few lines down:
{$tags -contains 'ErrorLog'}

This has the effect of search the entire $tags array for that string. When it finds one, it then initiates a search of the error logs. The problem is that this doesn't act on the 'current element in the array', it looks at every element in the $tags array. So, we loop over every element of the array and if any element of the array is 'ErrorLog', we search the same error logs over and over. this takes a lot of time for large logs and lead to my daily checks going from 0.75 to 2.5 hours. Disabling all ErrorLog checks dropped the running time back to normal.

That line should be:
{'ErrorLog'}

This will cause the search for interesting ErrorLog records to occur once per invocation of the switch statement.

**Comment by SQLDBAWithABeard** [comment]
closed with #636
