### ISSUE TITLE
policy.errorlog.warningwindow not fully honored, leading to failed tests

### ISSUE THREAD

**Issue by ashdar** [sqlcollaborative/dbachecks#637]
### General Troubleshooting steps
- [X] Verified running the latest release of dbachecks? 
- [X] Verified errors are not related to permissions?

### Version Information
 - Operating System (Name|Version): Windows 7
 - PowerShell Version: 5.1

### Steps to Reproduce
<--  
  PLEASE include as much information as possible if this is a bug report.
  The more you include the faster we can identify the problem and get it fixed
-->
To reproduce, all you need to do is to check the errorlog for an instance that has been up for a long while and has high-severity errors that occurred before the policy.errorlog.warningwindow starts.

### Description of Bug
The behavior is that policy.errorlog.warningwindow is not fully checked, resulting in "old" high-severity errors causing failed tests. 

In Instance.Assertions.ps1, Get-ErrorLogEntry does check the CreateDate of each log against policy.errorlog.warningwindow. This is effective as a performance tweak because searching logs that predate the policy.errorlog.warningwindow is pointless and time-consuming. 

BUT, the LogDate of each error record must also be checked because not every site rotates their logs on a daily (or weekly or even monthly) basis and the current log can easily have "old" errors. 

I will be submitting a patch for this shortly.
<--  
  PLEASE include as much information as possible if this is a bug
Explain what it does that you would like it not to do
or
What it doesnt do that you would like it to do :-)
-->

**Comment by SQLDBAWithABeard** [comment]
closed with #638
