### ISSUE TITLE
CIS checks

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#643]
related to #116 I think it is worth having an individual issue to track the progress of adding CIS checks to the module - CIS Project created https://github.com/sqlcollaborative/dbachecks/projects/1

- [ ] Write missing checks - This includes writing the tests for the checks, using assertions and performance (ie gathering all information in one visit to the instance See https://github.com/sqlcollaborative/dbachecks/blob/3d2166c81bbfc4f511f7edbe79eee5fd91f46b40/internal/assertions/Server.Assertions.ps1#L11)

[CIS_Audit_Matrix.xlsx](https://github.com/sqlcollaborative/dbachecks/files/3440922/CIS_Audit_Matrix.xlsx)

Attaching all the CIS benchmarks because they are slightly different for each version of SQL Server.
[CIS_Microsoft_SQL_Server_2017_Benchmark_v1.0.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417260/CIS_Microsoft_SQL_Server_2017_Benchmark_v1.0.0.pdf)
[CIS_Microsoft_SQL_Server_2008_R2_Benchmark_v1.6.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417261/CIS_Microsoft_SQL_Server_2008_R2_Benchmark_v1.6.0.pdf)
[CIS_Microsoft_SQL_Server_2012_Benchmark_v1.5.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417262/CIS_Microsoft_SQL_Server_2012_Benchmark_v1.5.0.pdf)
[CIS_Microsoft_SQL_Server_2014_Benchmark_v1.4.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417263/CIS_Microsoft_SQL_Server_2014_Benchmark_v1.4.0.pdf)
[CIS_Microsoft_SQL_Server_2016_Benchmark_v1.1.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417264/CIS_Microsoft_SQL_Server_2016_Benchmark_v1.1.0.pdf)

**Comment by SQLDBAWithABeard** [comment]
Will also assign @tboggiano when she has accepted information.

**Comment by SQLDBAWithABeard** [comment]
[CIS_Audit_Matrix.xlsx](https://github.com/sqlcollaborative/dbachecks/files/3440922/CIS_Audit_Matrix.xlsx)

Attaching all the CIS benchmarks because they are slightly different for each version of SQL Server.
[CIS_Microsoft_SQL_Server_2017_Benchmark_v1.0.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417260/CIS_Microsoft_SQL_Server_2017_Benchmark_v1.0.0.pdf)
[CIS_Microsoft_SQL_Server_2008_R2_Benchmark_v1.6.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417261/CIS_Microsoft_SQL_Server_2008_R2_Benchmark_v1.6.0.pdf)
[CIS_Microsoft_SQL_Server_2012_Benchmark_v1.5.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417262/CIS_Microsoft_SQL_Server_2012_Benchmark_v1.5.0.pdf)
[CIS_Microsoft_SQL_Server_2014_Benchmark_v1.4.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417263/CIS_Microsoft_SQL_Server_2014_Benchmark_v1.4.0.pdf)
[CIS_Microsoft_SQL_Server_2016_Benchmark_v1.1.0.pdf](https://github.com/sqlcollaborative/dbachecks/files/3417264/CIS_Microsoft_SQL_Server_2016_Benchmark_v1.1.0.pdf)

**Comment by wsmelton** [comment]
@SQLDBAWithABeard you might create this as a project in this repository. You can create items without creating each as an issue, then it lets you track the progress and what is completed a bit easier.

I found it easier at least than trying to cram everything into one issue.

**Comment by SQLDBAWithABeard** [comment]
https://github.com/sqlcollaborative/dbachecks/projects/1

**Comment by SQLDBAWithABeard** [comment]
What do we have left to do here @tboggiano ?
I think you have basically smashed it out of the park

**Comment by tboggiano** [comment]
Yeap smashed.  Now onto STIG after Summit.
