### ISSUE TITLE
CIS Check Ensure Latest SQL Service Packs and Hotfixes are Installed

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#644]
Ensure Latest SQL Service Packs and Hotfixes are Installed

**Comment by tboggiano** [comment]
Thinking this test might need to have the version numbers hard coded in because you may be running this module from a machine that doesn't have access to the Internet?

**Comment by SQLDBAWithABeard** [comment]
But we will have dbatools though which will have a cache
