### ISSUE TITLE
CIS Check Ensure 'CLR Enabled' Server Configuration is set to '0'

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#646]
Ensure 'CLR Enabled' Server Configuration is set to '0'

**Comment by tboggiano** [comment]
This test is already written and running under the CIS tag, so I believe we can close it.

**Comment by tboggiano** [comment]
Covered under #681 

#681

**Comment by tboggiano** [comment]
Taken care in new PR for Set-DbcCisConfig.
