### ISSUE TITLE
CIS Check Ensure 'Database Mail XPs' Server Configuration is set to '0'

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#648]
Ensure 'Database Mail XPs' Server Configuration is set to '0'

**Comment by tboggiano** [comment]
This is one where a test exist for the opposite value put for CIS needs to be disabled to pass.  Not sure how we will handle custom values for things that test differently for CIS.

**Comment by SQLDBAWithABeard** [comment]
I think that that will be covered under #681 

https://github.com/sqlcollaborative/dbachecks/issues/681

**Comment by tboggiano** [comment]
Set-DbcCisConfig takes care of setting to opposite value for testing.
