### ISSUE TITLE
CIS Check Ensure Database and Application User Input is Sanitized

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#675]
Ensure Database and Application User Input is Sanitized

**Comment by tboggiano** [comment]
The only test that can be done here is if INSERT, UPDATE, or DELETE permissions have been given the rest has to be done via other good practices.

**Comment by tboggiano** [comment]
This can't be tested so closing, there just has to be good security polices in place.
