### ISSUE TITLE
CIS Check Ensure 'CLR Assembly Permission Set' is set to 'SAFE_ACCESS' for All CLR Assemblies

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#676]
Ensure 'CLR Assembly Permission Set' is set to 'SAFE_ACCESS' for All CLR Assemblies

**Comment by tboggiano** [comment]
Close #734

**Comment by sivamca2126** [comment]
May I know solution for this issue?

**Comment by SQLDBAWithABeard** [comment]
For this github issue,  the check was written and incorporated into dbachecks so that you can test the setting
