### ISSUE TITLE
Possible - Specific CIS PowerBi file ?

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [sqlcollaborative/dbachecks#682]
Possible - Specific CIS PowerBi file ?

**Comment by ClaudioESSilva** [comment]
Let me know what type of info should be shown in a different way and maybe I can pick this one.

**Comment by tboggiano** [comment]
I don't think we need this unless we want the auditors to see a specific title that indicates CIS.  So maybe should just close this?

**Comment by SQLDBAWithABeard** [comment]
I think the 2 Power Bi files have the capability for people to beable to filter with those checks and so its not needed
