### ISSUE TITLE
DefaultTrace check succeeds when run individually but fails when run as part of Instance checks.

### ISSUE THREAD

**Issue by garyhampson** [sqlcollaborative/dbachecks#696]
### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? 

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`

![image](https://user-images.githubusercontent.com/6729780/37113488-60e5e172-21fa-11e8-8115-814edfbfabb6.png)

- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Microsoft Windows Server 2016 Datacenter  
 - PowerShell Version: 5.1.14393.3053
 - SQL Server (Edition|Version): Microsoft SQL Server 2016 (SP2-CU7-GDR) (KB4505222) - 13.0.5366.0 (X64)   Jun 15 2019 08:22:25   Copyright (c) Microsoft Corporation  Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 

### Steps to Reproduce
`Invoke-DbcCheck -SqlInstance GARYSQL01 -ComputerName GARYSQL01 -Check Instance`
`Invoke-DbcCheck -SqlInstance GARYSQL01 -ComputerName GARYSQL01 -Check DefaultTrace`
 - [x] Attach any screenshots (if possible/allowed)
 - [x] Attach output from PowerShell console (if possible/allowed)

`Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.2.12\checks\Instance.Tests.ps1
.
.
.
    Describing Ad Hoc Distributed Queries

    Context Testing Ad Hoc Distributed Queries on GARYSQL01
      [+] Ad Hoc Distributed Queries is set to False on GARYSQL01 44ms

  Describing XP CmdShell

    Context Testing XP CmdShell on GARYSQL01
      [+] XPCmdShell is set to False on GARYSQL01 44ms
  
  Describing Default Trace

    Context Checking Default Trace on GARYSQL01
      [-] The Default Trace should be enabled on GARYSQL01 7ms
        Expected 1, because We expect the Default Trace to be enabled but got, but got 'We Could not Connect to $Instance'.
        117:     $AllInstanceInfo.DefaultTrace.ConfiguredValue | Should -Be 1 -Because "We expect the Default Trace to be enabled but got $($AllInstanceInfo.DefaultTrace.Trace.ConfiguredValue)"
        at Assert-DefaultTrace, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.2.12\internal\assertions\Instance.Assertions.ps1: line 117
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.2.12\checks\Instance.Tests.ps1: line 809`

`Executing script C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.2.12\checks\Instance.Tests.ps1

  Describing Default Trace

    Context Checking Default Trace on GARYSQL01
      [+] The Default Trace should be enabled on GARYSQL01 4ms
Tests completed in 1.09s
Tests Passed: 1, Failed: 0, Skipped: 0, Pending: 0, Inconclusive: 0 `

### Description of Bug

The DefaultTrace check fails saying it cannot connect to the Sql Instance when run as part of the full Instance checks, but runs successfully when run as an individual check. The preceding checks (Ad-Hoc distributed queries and xp_cmdshell) do not have any issues connecting to the instance when run as part of the full Instance checks.

**Comment by garethnewman** [comment]
can re-produce, will have a look. Thanks.

**Comment by garethnewman** [comment]
issue seems to be with $There at this block, we hit the else when running instance checks

`'DefaultTrace' {
            if ($There) {
                try {
                    $SpConfig = Get-DbaSpConfigure -SqlInstance $Instance -ConfigName 'DefaultTraceEnabled'
                    $DefaultTrace = [pscustomobject] @{
                        ConfiguredValue = $SpConfig.ConfiguredValue
                    }
                }
                catch {
                    $There = $false
                    $DefaultTrace = [pscustomobject] @{
                            ConfiguredValue = 'Exception: We Could not Connect to $Instance'
                    }
                }
            }
            else {
                $There = $false
                $DefaultTrace = [pscustomobject] @{
                        ConfiguredValue = 'We Could not Connect to $Instance'
                    }
            }
        }`

**Comment by garethnewman** [comment]
Update: all the checks fail for instance that use this function: Get-AllInstanceInfo inside Instance.Assertions.ps1

**Comment by garethnewman** [comment]
all seems to be around here
`
function Get-AllInstanceInfo {
    # Using the unique tags gather the information required
    Param($Instance, $Tags, $There)
    # Using there so that if the instance is not contactable, no point carrying on with gathering more information
    switch ($tags) {
        'ErrorLog' { 
            if ($There) {
                try {
`

before switch ($tags) $There = $true after switch ($tags) $There = $false ???

**Comment by garyhampson** [comment]
Hi @garethnewman  - I think I've found the root cause of the issue. In the Instance.Assertions.ps1 file, this line needs to be changed:

`Count = (Get-DbaDump -SqlInstance $psitem -WarningAction SilentlyContinue).Count
`
to 

`Count = (Get-DbaDump -SqlInstance $Instance -WarningAction SilentlyContinue).Count`

Once I did that in my local, I didn't have this issue. The $There value was getting set to $false because the call to Get-DbaDump in the MemoryDump section was failing due to the wrong parameter being used in the call to that function.

**Comment by garethnewman** [comment]
Hey Gary, good work, seems like you found it quicker than I did! I need to learn how to debug powershell. I put Write-Host everywhere to find it! :) if you see above I raised a PR that will fix this where I come to the exact same conclusion, so we can't both be wrong! :)

**Comment by garyhampson** [comment]
Hi @garethnewman - Have to get my eyes checked, because I didn't see that you had a pull request, so thanks for that! Can confirm that your proposed solution will fix this issue.

**Comment by tboggiano** [comment]
I've tried this fix and it seems to only work if default trace is enabled.  Plus this line looks to be incorrect

 `$AllInstanceInfo.DefaultTrace.ConfiguredValue | Should -Be 1 -Because "We expect the Default Trace to be enabled but got $($AllInstanceInfo.DefaultTrace.Trace.ConfiguredValue)" `

As there is no .Trace value for the last AllInstanceInfo reference.  Even with that corrected with Default Trace disabled I still get an error.

![DefaultTraceEnabled](https://user-images.githubusercontent.com/26776763/63096566-3b93dd80-bf3c-11e9-8da4-9462b37f15df.png)
![DefaultTraceDisabled](https://user-images.githubusercontent.com/26776763/63096568-3d5da100-bf3c-11e9-8b0b-f7f9d6e47acf.png)

I don't know what the answer is but when I write similar test for RemoteAccess and ScanForStartupProcdures I get the exact same thing.

**Comment by garethnewman** [comment]
Hey, I think my PR should fix this. Feel free to test it.

**Comment by tboggiano** [comment]
OK.  I see based on other things failing it spitting out all that red is ok, I still question the one line of code if that $($AllInstanceInfo.DefaultTrace.Trace.ConfiguredValue) is correct, there is no .Trace value from what I can see it should be just $($AllInstanceInfo.DefaultTrace.ConfiguredValue) at the end.

**Comment by garethnewman** [comment]
Ahh, ok yeah that looks like another issue, I only tested with trace enabled to look at Gary's specific issue of instance checks vs defaulttrace check.
