### ISSUE TITLE
Incorrect calculation of "Last agent run time" check

### ISSUE THREAD

**Issue by NeilWinder** [sqlcollaborative/dbachecks#703]
#698  Bug Report
In the last check of Agent.Tests.ps1 the average run_duration is being correctly converted from the run_duration format of HHMMSS, but then the average is compared to the raw run_duration.

### General Troubleshooting steps
Example: My average run_duration is 1071 seconds. The run_duration for the last job shows 1703 (17:03) so the check fails. Converting 1703 to seconds ((17*60) + 3) yields 1023 which would pass.

Changing this line:
jh.run_duration AS Duration

to this:
DATEDIFF(SECOND, 0, STUFF(STUFF(RIGHT('000000' + CONVERT(VARCHAR(6),jh.run_duration),6),5,0,':'),3,0,':')) AS Duration

resolves the problem.

**Comment by SQLDBAWithABeard** [comment]
closed with #746
