### ISSUE TITLE
Describing Remote Access Disabled don't understand ish

### ISSUE THREAD

**Issue by PsPsam** [sqlcollaborative/dbachecks#712]
### Question
I'm not following the logic in the error message.
If I understand the test correctly it test if it can remote access the sql server. If it can it will return a 1(true) and if not a 0 (false).

The setting it tests is "Allow remote connections to this server". So if I have this checked should the setting "policy.security.remoteaccessdisabled" be true or false? 

In the default settings this is set to 0. For me that suggests that "remoteaccessdisabled" is false meaning that we allow remote connections to the server. But having the setting on the sql server allowing remote connections will make the default settings make it fail. as shown below.

So the question is why does the setting have "disabled" in it? For it to work you have to enabled it as the "Description": "Remote Access should be disabled 0 or enabled 1" says.  I think the settings name and the description contradict each other.

It makes me very confused 🤔

I do like the test though 👍 

 ```
Describing Remote Access Disabled

   Context Testing Remote Access on NP:.
      [-] The Remote Access should be disabled on NP:. 4ms
        Expected 0, because We expected Remote Access to be enabled, but got 1.
        256:     $AllInstanceInfo.RemoteAccessDisabled.ConfiguredValue | Should -Be 0 -Because "We expected Remote Access to be enabled"
        at Assert-RemoteAccess, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.2.14\internal\assertions\Instance.Assertions.ps1: line 256
        at <ScriptBlock>, C:\Program Files\WindowsPowerShell\Modules\dbachecks\1.2.14\checks\Instance.Tests.ps1: line 849
```

**Comment by tboggiano** [comment]
This has been fixed in another PR to say disabled.

**Comment by SQLDBAWithABeard** [comment]
Yes, we added confusion - the reason for the disabled was that this is a CIS test which expects CIS to be disabled
