### ISSUE TITLE
HADR  : Errors when empty availability group

### ISSUE THREAD

**Issue by conseilit** [sqlcollaborative/dbachecks#737]
Hi everyone

## Bug Report

When running Invoke-DbcCheck -Check HADR 
Some errors raise because the $AG variable is NULL for Availability Groups with no databases.

$AGs variable is filled with multiple entries. The name property is correct but  Value is empty.

## Version
Currently using
Pester v4.9.0
dbachecks v1.2.22

## Workaroud
Adding something like 
            if (!($Ag)){continue}
line 125 of the HADR.tests.ps1 file removes the error.

**Comment by mikedavem** [comment]
In addition, AG replicas based on named instances or instances that listen to non default port seem to not be handled correctly 

`Get-DbaAvailabilityGroup -SqlInstance $Ag.OwnerNode.Name -AvailabilityGroup $AG.Name
`
Regards
