### ISSUE TITLE
Disk exclusion not effective with DiskAllocationUnit check

### ISSUE THREAD

**Issue by mikedavem** [sqlcollaborative/dbachecks#738]
### General Troubleshooting steps
- [X] Verified running the latest release of dbachecks? 

```
> (Find-Module dbachecks).Version
Major  Minor  Build  Revision
-----  -----  -----  --------
1      2      24     -1

> (Get-Module dbachecks).Version.ToString()
1.2.24
```

- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows Server 2016 Datacenter 10.0 - Build 14393
 - PowerShell Version: 5.1.17763.771
 - SQL Server (Edition|Version): 2017 Enterprise| RTM-CU14

### Steps to Reproduce

```
> Set-DbcConfig -Name policy.server.excludeDiskAllocationUnit -Value C:\
Name                                    Value Description
----                                    ----- -----------
policy.server.excludeDiskAllocationUnit C:\   The disks to skip from the Disk Allocation Unit check - Must be 'DISKLETTER:\'

> Invoke-DbcCheck -ComputerName xxxx -Checks DiskAllocationUnit
Describing Disk Allocation Unit

    Context Testing disk allocation unit on xxxx
      [!] C:\ Should be set to 64kb on xxxx, is skipped 0ms
      [!] D:\ Should be set to 64kb on xxxx, is skipped 0ms
      [!] L:\ Should be set to 64kb on xxxx is skipped 0ms
Tests completed in 3.6s
Tests Passed: 0, Failed: 0, Skipped: 3, Pending: 0, Inconclusive: 0
```

 - [ ] Attach any screenshots (if possible/allowed)
 - [X] Attach output from PowerShell console (if possible/allowed)

### Description of Bug
When configuration disk exclusion (parameter **policy.server.excludeDiskAllocationUnit**), some disk allocation unit tests are skipped and should not.

**Comment by shaneis** [comment]
I did a quick test to see if I can reproduce this and I can. From talking with  @mikedavem he seems to have a handle on the root cause. I'll let him explain 👍
