### ISSUE TITLE
Pester 5 Incompatibility

### ISSUE THREAD

**Issue by LowlyDBA** [sqlcollaborative/dbachecks#774]
### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? 

2.0.3

- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System: Windows Server 2016 10.0.14393
 - PowerShell Version: 5.1.14393.3471

### Description of Bug

With Pester 5 now released, there should be a call out in the documentation that the current version of dbachecks is not compatible + a version limit when loading the module implicitly.

I spent a few hours scratching my head setting dbachecks up on a new box only to realize that was the core of a *bunch* of interesting errors.

**Comment by SQLDBAWithABeard** [comment]
Hmm, yes that is not a good thing.

I have had a couple of goes at trying to fix this in the psd1, I may have to find a different way

**Comment by awickham10** [comment]
I also ran into some head scratching with Pester 5. Running the recovery model checks against a single server with 30 databases was taking 7 minutes to complete. I unloaded Pester 5 and loaded Pester 4.9 and it took 1.25 seconds.
