### ISSUE TITLE
 Invoke-DbcCheck fails for DB without LogShipping, it stops the dbacheck session in 2.0.4

### ISSUE THREAD

**Issue by Lemengo** [sqlcollaborative/dbachecks#788]
### Version Information
 - Operating System (Name|Version): Windows Server 2019 Datacenter
 - PowerShell Version: 5.1.17763.592
 - SQL Server (Edition|Version): Microsoft SQL Server 2019 (RTM)

### Steps to Reproduce
Run something like : 
<--  
  Invoke-DbcCheck -SqlInstance BDSRV01 -AllChecks  -Show Summary -PassThru
-->
![image](https://user-images.githubusercontent.com/20980143/89436785-b5f0db00-d714-11ea-81c9-005b658d831a.png)

**Comment by Ant-Green** [comment]
@Lemengo 

DBAChecks doesn't currently work with Pester 5, believe @SQLDBAWithABeard  is working on a fix for this.

For now if you uninstall Pester 5 and install Pester 4.10.1 and everything should work until the Pester 5 fixes are deployed.

**Comment by SQLDBAWithABeard** [comment]
Pester 5 woes but now we remove the module and use the version that works.
One day I will get whats in my head into code
