### ISSUE TITLE
Unable to execute dbacheck commands

### ISSUE THREAD

**Issue by SaravanaKumarRamesh** [sqlcollaborative/dbachecks#797]
## Issue

i installed dbachecks module in a server. but when i am trying to execute get-dbccheck, it is throwing the below error

> Populating RepositorySourceLocation property for module Pester.
> VERBOSE: Loading module from path 'C:\Program Files\WindowsPowerShell\Modules\Pester\5.0.4\Pester.psm1'.
> [18:59:41][dbachecks.psm1] Failed to import suitable version - Do you have Version 4* installed ?
> Get-DbcCheck : The 'Get-DbcCheck' command was found in the module 'dbachecks', but the module could not be loaded. For more information, run 'Import-Module dbachecks'.
> At line:1 char:1
> + Get-DbcCheck
> + ~~~~~~~~~~~~
>     + CategoryInfo          : ObjectNotFound: (Get-DbcCheck:String) [], CommandNotFoundException
>     + FullyQualifiedErrorId : CouldNotAutoloadMatchingModule

This is a question

### General Troubleshooting steps
- [ ] Verified running the latest release of dbachecks?  - Yes.

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`  - i am unable to execute (Get-Module dbachecks).Version.ToString() - it is throwing error saying " You cannot call a method on a null-valued expression"

![image](https://user-images.githubusercontent.com/6729780/37113488-60e5e172-21fa-11e8-8115-814edfbfabb6.png)

- [ ] Verified errors are not related to permissions?  - I have admin permissions on the Server
- [ ] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version): Windows server 2012 R2| 6.3.9600
 - PowerShell Version: 5.1.14409.1018
 - SQL Server (Edition|Version): Standard | 2012,2014,2016

**Comment by Ant-Green** [comment]
You have pester 5.0.4 installed and you need pester 4.10.1.  Uninstall and reinstall pester to the required version and please retry.

Also look at updating DBA checks, latest build is 2.0.7.

**Comment by SaravanaKumarRamesh** [comment]
Hi Ant-Green
thank you so much..it worked..
