### ISSUE TITLE
Unable to find type [Pester.OutputTypes]

### ISSUE THREAD

**Issue by sgreci** [sqlcollaborative/dbachecks#798]
Hello,

**Version Information**
Operating System (Name|Version): Windows 10 2004
PowerShell Version: 5.1.19041.1
SQL Server (Edition|Version): Microsoft SQL Server 2019 (RTM)

**Steps to Reproduce**

Installed dbachecks with no errors:

`Install-Module dbachecks`

Execute:

`Invoke-DbcCheck`

I got this error:

```
Unable to find type [Pester.OutputTypes].
At line:219 char:9
+         [Pester.OutputTypes]$Show = 'All'
+         ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Pester.OutputTypes:TypeName) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound
```

Running Get-InstalledModule, looks like Pester is not installed:

```
Version    Name                                Repository           Description
-------    ----                                ----------           -----------
2.0.7      dbachecks                           PSGallery            SQL Server Infrastructure validation Tests to en...
1.0.124    dbatools                            PSGallery            The community module that enables SQL Server Pro...
1.4.150    PSFramework                         PSGallery            General Scripting Framework, providing PowerShel...
```

**Comment by Ant-Green** [comment]
Pester is no longer installed by the module as it try’s to download Pester5 when only Pester4 works.

As such can you also run

Install-module pester -requiredversion 4.10.1

And then retry the invoking of the checks.

**Comment by sgreci** [comment]
Thanks @Ant-Green 

I've forced installation of Pester 4.10.1 but same results. Tried also to reproduce on a different box (Windows 2019 Datacenter on Azure) and gave me some different errors, that lead me to this article:

https://www.alitajran.com/unable-to-install-nuget-provider-for-powershell/

Settings this 2 registry keys + installing Pester 4.10.1 fixed the issue and I can execute without errors Dbchecks commandlets:

```
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
Set-ItemProperty -Path 'HKLM:\SOFTWARE\Wow6432Node\Microsoft\.NetFramework\v4.0.30319' -Name 'SchUseStrongCrypto' -Value '1' -Type DWord
```
I didn't dig a lot in the issue but it looks like that some .NET updates disabled some security protocols that are necessary to works properly.

Ciao.

**Comment by Ant-Green** [comment]
I've not tried running it with the new PSFramework yet so unsure if that's causing an issue now also like Pester 5 did

Could you uninstall PSFramework 1.4.150 and install 1.1.59

Then can you provide an updated Get-InstalledModule output

**Comment by sgreci** [comment]
@Ant-Green 

Cleaned-up all installed modules and installed the modules as you suggest:
```
Install-Module PSFramework -RequiredVersion 1.1.59
Install-Module Pester -RequiredVersion 4.10.1 -Force -SkipPublisherCheck
Install-Module dbachecks

```
Get-InstalledModule output:

```
Version    Name       
-------    ----       
2.0.7      dbachecks  
1.0.124    dbatools   
4.10.1     Pester     
1.1.59     PSFramework
```

I rollback the 2 registry keys about the Crypto in .NET and Invoke-DbcCheck run without errors:

```
PS C:\WINDOWS\system32> Invoke-DbcCheck
WARNING: [10:49:07][Invoke-DbcCheck] Please specify Check, ExcludeCheck, Script, TestName or AllChecks
```

I need to reproduce the same on a clean machine on Azure and confirm.

**Comment by Ant-Green** [comment]
Thanks so it seems the new PSFramework has breaking changes also like Pester 5 did, good to know I wont roll it out now.

Will do some debugging see if I can figure out what's going on with the new version.

**Comment by SQLDBAWithABeard** [comment]
closed as stale

**Comment by potatoqualitee** [comment]
![image](https://user-images.githubusercontent.com/8278033/140947770-96ecb02b-311e-42b0-9fd4-b3810534042f.png)

I'm getting this error too, so right now, dbachecks doesn't work out of the box and requires googling to solve the issue. 

Can we handle this in the psm1 somehow?

**Comment by potatoqualitee** [comment]
ahh okay, pester version 3.4.0 does not support that output type.

![image](https://user-images.githubusercontent.com/8278033/140951812-d4affa1c-2c2a-40fd-a7e6-b8bae876b507.png)

![image](https://user-images.githubusercontent.com/8278033/140951838-1fd7f99e-02fe-4c55-af7d-193904d8c352.png)


will submit a PR
