### ISSUE TITLE
PowerBI (original) Issue with column in table 

### ISSUE THREAD

**Issue by jpomfret** [sqlcollaborative/dbachecks#800]
### General Troubleshooting steps
- [X] Verified running the latest release of dbachecks? 
![image](https://user-images.githubusercontent.com/981370/95421997-65754400-0936-11eb-92d5-8ab6a0c01f57.png)

- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System (Name|Version):  Win 10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): SQL Server 2017

### Steps to Reproduce
- Run two checks against two machines and save to json file
```
Invoke-DbcCheck -SqlInstance mssql1,mssql2 -Check Databasestatus, PageVerify -Passthru | Update-DbcPowerBiDataSource
Start-DbcPowerBi
```

- Dashboard shows wrong column in table (Source instead of Describe)
![image](https://user-images.githubusercontent.com/981370/95422124-a705ef00-0936-11eb-87a4-310e76b44af3.png)

### Description of Bug
Table on PowerBi report shows the wrong test name for the failures, it seems to be taking the name from part of the json file that is exported, instead of using the describe. I have poked around and haven't found a reason why it might be doing that.

Looking at the data source for PowerBi to work out where the column came from:
![image](https://user-images.githubusercontent.com/981370/95422445-40cd9c00-0937-11eb-8650-5bae7446c4c2.png)

### Potential Fix
Could we just change the column used in this table?
![image](https://user-images.githubusercontent.com/981370/95422348-0e23a380-0937-11eb-82c4-609d35a46467.png)

**Comment by ClaudioESSilva** [comment]
Hi @jpomfret , good catch! 👍 

Some versions ago, on v.1.1.122, the source column had the "environment" value.
This changed over time and right now we have both "Environment" and "Source", however "source" seems not to be perfectly shread from the filename.

As we agreed, I have replaced the "Source" by "Describe" on the pbix and also generated a new pbit.

Can you grab by branch download the files and test it? 😄 
Thanks!
