### ISSUE TITLE
Install-Module DBAChecks fails due to dependency on Pester v4.X after it installs dependency Pester v5.X, good workaround?

### ISSUE THREAD

**Issue by dave-007** [sqlcollaborative/dbachecks#802]
### Question
Am I doing this right? Does Pester release of version 5 break dbachecks?

I just installed dbachecks from scratch with `Install-Module dbachecks`
Spent a lot of time debugging the error that occurs when running `Invoke-DbcCheck` for the first time:
` Failed to import suitable version - Do you have Version 4* installed`
Turns out dbachecks installs the module dependencies at their latest versions, including Pester, which now is at version 5.0.4
However dbachecks depends on Pester 4.X. Thus the error above.

This may be a recently surfaced issue as Pester 5 was release in May.

My workaround is to install Pester at 4.X:

`Install-Module pester -MaximumVersion 4.9`

then install dbachecks

`Install-Module dbachecks -Verbose`

**Comment by Ant-Green** [comment]
V2.0.7 of the checks took pester out as a dependent module due to Pester5 having a lot of breaking changes as you have noticed.

If you have pester 5.0.0 or above it’ll need to be uninstalled and pester 4.10.1 installed instead.

I believe Rob is looking at changes for Pester5 to make DBA checks compliant with that version of the module.

**Comment by dave-007** [comment]
I suggest changing https://dbachecks.readthedocs.io/en/latest/
Change
`Install-Module Pester -SkipPublisherCheck -Force`
to 
`Install-Module Pester -SkipPublisherCheck -MaximumVersion 4.9 -Force`

I tried to make this change myself as PR, but edit [link](https://github.com/sqlcollaborative/dbachecks/edit/master/docs/index.md) up top is broken, happy to take that route with some guidance.

**Comment by Ant-Green** [comment]
No problem I’ll put a PR in for it I have a change to push for some code changes so I’ll take that on for you.
