### ISSUE TITLE
Adding category exclusion / inclusion lists  for ValidJobOwner check

### ISSUE THREAD

**Issue by mikedavem** [sqlcollaborative/dbachecks#823]
## Feature Request
   
Currently, checking job valid owner is performed without any exclusions meaning all jobs within one SQL Instance must have the same owner. This doesn't represent always real scenarios where a mix of owners may exist.
   
## New Check

New check should introduce a way to include or exclude job categories for this check. From my opinion using categories are simpler than using directly job names. 

### What should be configurable for the results of the check ?

List of categories to exclude
List of categories to keep for check
No default values

**Comment by SQLDBAWithABeard** [comment]
the valid job owner config allows multiple values, does that fulfil your need?

**Comment by SQLDBAWithABeard** [comment]
valid job owner config allows multiple values
