### ISSUE TITLE
Maintenance Solution retention time check issues

### ISSUE THREAD

**Issue by mikedavem** [sqlcollaborative/dbachecks#835]
### General Troubleshooting steps
- [X ] Verified running the latest release of dbachecks? 

2.0.9

- [ X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Version Information
 - Operating System : Windows Server 2016 / Windows 10
 - PowerShell Version: 5.1
 - SQL Server (Edition|Version): EE/2017

### Steps to Reproduce
When policy.ola.DeleteBackupHistoryCleanUp value is over 2 digits the check is failing.
Let's say I want to keep more 2 years of backup history (~730days) , the check is designed to keep only 2 digits -> 73

 - [X ] Attach any screenshots (if possible/allowed)

![image](https://user-images.githubusercontent.com/29414235/111134166-a293d100-857b-11eb-8f7e-ebd08be2de91.png)

 - [ ] Attach output from PowerShell console (if possible/allowed)

### Description of Bug

The description of the parameter doesn't suggest any limits for days

![image](https://user-images.githubusercontent.com/29414235/111134374-d7a02380-857b-11eb-98f3-691eb35165b8.png)

but the related check code is limited to 2 digits

`$days = [regex]::matches($jobsteps.Command, "dd,-(\d\d)").groups[1].value`

We could improve the code as follows to make detection more dynamic:

`$days = [regex]::matches($jobsteps.Command, "dd,-(\d*)").groups[1].value`

The same applies for 
- File Job Cleanup Time
- Delete Backup History Cleanup Time
- Delete Purge History Cleanup Time

**Comment by SQLDBAWithABeard** [comment]
Closed with 35bb7873444c0012d33cdf992d74a3619aaf99c2
