### ISSUE TITLE
cmdlet aliases not always supported in PSCore

### ISSUE THREAD

**Issue by Shashtsoh** [sqlcollaborative/dbachecks#837]
I ran into an issue while training a colleague today. He's using a Mac running PSCore.  We couldn't get past the pester version check until we realized that the "sort" command error it was throwing was for the bash sort command.  Per https://github.com/PowerShell/PowerShell/issues/6684 the Sort alias for Sort-Object was removed due to the sort command already being present in bash.  We edited his dbachecks.psm1 to change "... | Sort Version ..." to "... | Sort-Object Version..." and were able to get past the error.

Aliases should probably be removed for cross-platform compatibility.

**Comment by SQLDBAWithABeard** [comment]
thank you :-) fixed in next release
