### ISSUE TITLE
Examples formatting

### ISSUE THREAD

**Issue by MikeyBronowski** [sqlcollaborative/dbachecks#839]
### Question

Examples in the docs are formatted in the generic code block. Would it make sense to add PowerShell formatting to the blocks containing actual PowerShell commands?

This PR has an example of that change #838 .

**Comment by SQLDBAWithABeard** [comment]
Unfrotunately - that is controlled by the New-MarkdownHelp command in the buildthedocs.ps1 file and we dont have control over it.
