### ISSUE TITLE
Convert-DbcResult returns only last pester.testresult

### ISSUE THREAD

**Issue by SteveCInVA** [sqlcollaborative/dbachecks#846]
### General Troubleshooting steps
- [x] Verified running the latest release of dbachecks? 
- [x] Verified errors are not related to permissions?
- [x] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Steps to Reproduce

1. Configure custom test and configure the path to the test in app.checkrepos (set-dbcconfig -name app.checkrepos -value "D:\tests\" -append
2. Invoke-DbcCheck -SqlInstance SQL2017N5 -Check AutoClose -Passthru | Convert-DbcResult -Label Beard-Check | Set-DbcFile -FilePath C:\temp\dbachecks\ -FileName Auto-close.json -FileType Json

You will notice the auto-close.json file has 0 items reported even if the initial test failed.

### Description of Bug

If custom user tests are configured in app.checkrepos (even if not executed) test results passed to Convert-DbcResult only returns the last test result object.  

One would expect multiple test results to be aggregated into a single system.data.datatable object.

**Comment by ashdar** [comment]
I think that the last release (2.0.14) was the day before this fix was added (August 24, 2021). Is there another release in the offing?
