### ISSUE TITLE
Add replication procs as exceptions to startup procs

### ISSUE THREAD

**Issue by tboggiano** [sqlcollaborative/dbachecks#848]
## Feature Request
   
Leave out replication procs as procs that startup procs check checks for.
   
### What should be configurable for the results of the check ?
    
I need to get a full list, let me find them on MS's website.

<-- Should there be any default values for the configs? -->   
Yes.

**Comment by SQLDBAWithABeard** [comment]
If someone can get hte full list this should be easy to implement

**Comment by tboggiano** [comment]
I will get a list for us.

**Comment by tboggiano** [comment]
That was way simpler than expected, I put this really as a placeholder to cleanup CIS checks on startup procedures but there is only on sp_MSrepl_startup and checkout the name.

**Comment by tboggiano** [comment]
Accomplished in https://github.com/sqlcollaborative/dbachecks/pull/863.
