### ISSUE TITLE
File Convert-ConfigValueToBoolean.ps1 is zero-length

### ISSUE THREAD

**Issue by ashdar** [sqlcollaborative/dbachecks#861]
## Bug Report
This is a minor issue, but I happened to notice that the file "./internal/functions/Convert-ConfigValueToBoolean.ps1" is a zero length file and has no content. 

I don't see a function named "Convert-ConfigValueToBoolean" begin mentioned in any ps1 file . 

This file still exists in 2.0.14.

I believe that the fix is to remove the file, which seems too easy to bother with a new fix branch and a pull request.

### General Troubleshooting steps
- [X] Verified running the latest release of dbachecks? 

Does `(Find-Module dbachecks).Version match (Get-Module dbachecks).Version.ToString()`
Yes.

- [X] Verified errors are not related to permissions?
- [X] Can duplicate in new/clean PowerShell session (clean = `powershell -NoProfile`)?

### Steps to Reproduce
There are no reported errors or misbehaviors that I can see, but I'm a believer in "if we don't need it, it shouldn't be there".

**Comment by SQLDBAWithABeard** [comment]
thank you - i will push acommit to dev to remove this
